(function(){
'use strict';
var books={
 old:['Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth','1 Samuel','2 Samuel','1 Kings','2 Kings','1 Chronicles','2 Chronicles','Ezra','Nehemiah','Tobit','Judith','Esther','1 Maccabees','2 Maccabees','Job','Psalms','Proverbs','Ecclesiastes','Song of Songs','Wisdom of Solomon','Sirach','Isaiah','Jeremiah','Lamentations','Baruch','Ezekiel','Daniel','Hosea','Joel','Amos','Obadiah','Jonah','Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah','Malachi'],
 new:['Matthew','Mark','Luke','John','Acts','Romans','1 Corinthians','2 Corinthians','Galatians','Ephesians','Philippians','Colossians','1 Thessalonians','2 Thessalonians','1 Timothy','2 Timothy','Titus','Philemon','Hebrews','James','1 Peter','2 Peter','1 John','2 John','3 John','Jude','Revelation']
};
var chapters={'Genesis':50,'Exodus':40,'Leviticus':27,'Numbers':36,'Deuteronomy':34,'Joshua':24,'Judges':21,'Ruth':4,'1 Samuel':31,'2 Samuel':24,'1 Kings':22,'2 Kings':25,'1 Chronicles':29,'2 Chronicles':36,'Ezra':10,'Nehemiah':13,'Esther':10,'Job':42,'Psalms':150,'Proverbs':31,'Ecclesiastes':12,'Song of Songs':8,'Isaiah':66,'Jeremiah':52,'Lamentations':5,'Ezekiel':48,'Daniel':12,'Hosea':14,'Joel':3,'Amos':9,'Obadiah':1,'Jonah':4,'Micah':7,'Nahum':3,'Habakkuk':3,'Zephaniah':3,'Haggai':2,'Zechariah':14,'Malachi':4,'Matthew':28,'Mark':16,'Luke':24,'John':21,'Acts':28,'Romans':16,'1 Corinthians':16,'2 Corinthians':13,'Galatians':6,'Ephesians':6,'Philippians':4,'Colossians':4,'1 Thessalonians':5,'2 Thessalonians':3,'1 Timothy':6,'2 Timothy':4,'Titus':3,'Philemon':1,'Hebrews':13,'James':5,'1 Peter':5,'2 Peter':3,'1 John':5,'2 John':1,'3 John':1,'Jude':1,'Revelation':22};
var LAST='copticDailyPrayer_bibleLast_v1',SIZE='copticDailyPrayer_bibleSize_v1';
var omitted=['Tobit','Judith','1 Maccabees','2 Maccabees','Wisdom of Solomon','Sirach','Baruch'];
function id(x){return document.getElementById(x)}
function build(){
 var host=id('bible');if(!host||host.getAttribute('data-ready'))return;host.setAttribute('data-ready','1');
 host.innerHTML='<div class="bibleBrowser" id="bibleBrowser"><header class="pageHead bibleHead"><div class="eyebrow">Holy Scripture</div><h1>Bible</h1><p class="subtitle">A Coptic Orthodox Bible reader.</p></header><div class="bibleNotice"><strong>Bible reader foundation</strong><p>The reader is being prepared for the Coptic Orthodox canon. Full NKJV text will be added only through an authorized licensed source.</p></div><div class="bibleSearchWrap"><label class="srOnly" for="bibleBookSearch">Find a book</label><input id="bibleBookSearch" class="bibleBookSearch" type="search" placeholder="Find a book" autocomplete="off" spellcheck="false"></div><button class="bibleContinue hide" id="bibleContinue" type="button"><small>Continue reading</small><strong id="bibleContinueTitle"></strong><span>›</span></button><div class="serviceTabs bibleTabs" role="tablist"><button class="serviceTab active" type="button" data-testament="old">Old Testament</button><button class="serviceTab" type="button" data-testament="new">New Testament</button></div><div class="bibleBooks" id="bibleBooks"></div><p class="bibleSource">Canon structure follows Coptic Orthodox usage. The omitted canonical books are treated as Scripture, not as a separate “Apocrypha” section.</p></div><div class="bibleChapterView hide" id="bibleChapterView"><button class="bibleBack" id="bibleBack" type="button">‹ Books</button><div class="eyebrow">Choose Chapter</div><h1 id="bibleBookTitle"></h1><div class="chapterGrid" id="bibleChapterGrid"></div></div><div class="bibleReaderView hide" id="bibleReaderView"><button class="bibleBack" id="bibleReaderBack" type="button">‹ Chapters</button><div class="bibleReaderTop"><div><div class="eyebrow">Bible</div><h1 id="bibleReaderTitle"></h1></div><div class="bibleTextSize" aria-label="Text size"><button id="bibleSizeDown" type="button" aria-label="Decrease text size">A−</button><button id="bibleSizeReset" type="button" aria-label="Default text size">A</button><button id="bibleSizeUp" type="button" aria-label="Increase text size">A+</button></div></div><div class="bibleLicensePlaceholder"><strong>NKJV text source pending</strong><p>This chapter reader is ready. Scripture text will appear here once an authorized NKJV source is connected.</p></div><div class="bibleReaderNav"><button id="biblePrevChapter" type="button">‹ Previous</button><button id="bibleNextChapter" type="button">Next ›</button></div></div>';
 id('bibleBookSearch').oninput=function(){filterBooks(this.value)};id('bibleBack').onclick=showBooks;id('bibleSizeDown').onclick=function(){setSize(size()-1)};id('bibleSizeReset').onclick=function(){setSize(0)};id('bibleSizeUp').onclick=function(){setSize(size()+1)};id('bibleContinue').onclick=function(){var x=lastReading();if(x)openChapter(x.book,x.chapter)};id('bibleReaderBack').onclick=function(){showChapters(currentBook)};id('biblePrevChapter').onclick=function(){openChapter(currentBook,currentChapter-1)};id('bibleNextChapter').onclick=function(){openChapter(currentBook,currentChapter+1)};refreshContinue();var tabs=host.querySelectorAll('[data-testament]');for(var i=0;i<tabs.length;i++)tabs[i].onclick=function(){for(var j=0;j<tabs.length;j++)tabs[j].classList.toggle('active',tabs[j]===this);render(this.getAttribute('data-testament'))};render('old')
}
function filterBooks(q){q=String(q||'').toLowerCase().trim();var bs=document.querySelectorAll('#bibleBooks .bibleBook');for(var i=0;i<bs.length;i++){var n=(bs[i].getAttribute('data-book')||'').toLowerCase();bs[i].classList.toggle('hide',!!q&&n.indexOf(q)<0)}}
function render(which){var host=id('bibleBooks');if(!host)return;host.innerHTML='';var list=books[which]||[];for(var i=0;i<list.length;i++){var b=document.createElement('button'),name=list[i];b.type='button';b.className='bibleBook';b.innerHTML='<span></span><small>›</small>';b.querySelector('span').textContent=name;if(omitted.indexOf(name)>=0)b.setAttribute('data-canonical-omitted','1');b.setAttribute('data-book',name);b.onclick=function(){showChapters(this.getAttribute('data-book'))};host.appendChild(b)}}
var currentBook='',currentChapter=1;
function size(){try{return Math.max(-1,Math.min(2,Number(localStorage.getItem(SIZE)||0)))}catch(e){return 0}}function setSize(n){n=Math.max(-1,Math.min(2,n));try{localStorage.setItem(SIZE,String(n))}catch(e){}var r=id('bibleReaderView');if(r)r.setAttribute('data-text-size',String(n))}function lastReading(){try{var x=JSON.parse(localStorage.getItem(LAST)||'null');return x&&x.book&&x.chapter?x:null}catch(e){return null}}function refreshContinue(){var x=lastReading(),b=id('bibleContinue');if(!b)return;b.classList.toggle('hide',!x);if(x)id('bibleContinueTitle').textContent=x.book+' '+x.chapter}function showBooks(){id('bibleBrowser').classList.remove('hide');id('bibleChapterView').classList.add('hide');id('bibleReaderView').classList.add('hide');window.scrollTo(0,0)}
function showChapters(book){currentBook=book;id('bibleBrowser').classList.add('hide');id('bibleReaderView').classList.add('hide');id('bibleChapterView').classList.remove('hide');id('bibleBookTitle').textContent=book;var grid=id('bibleChapterGrid');grid.innerHTML='';var count=chapters[book]||0;if(!count){var note=document.createElement('p');note.className='bibleChapterPending';note.textContent='Chapter structure for this Coptic canonical book will be added with the authorized text source.';grid.appendChild(note)}else for(var n=1;n<=count;n++){var b=document.createElement('button');b.type='button';b.textContent=n;b.setAttribute('data-chapter',n);b.onclick=function(){openChapter(book,Number(this.getAttribute('data-chapter')))};grid.appendChild(b)}window.scrollTo(0,0)}
function openChapter(book,n){var count=chapters[book]||0;if(!count||n<1||n>count)return;currentBook=book;currentChapter=n;try{localStorage.setItem(LAST,JSON.stringify({book:book,chapter:n}));var rr=JSON.parse(localStorage.getItem(RECENT)||'[]');if(!Array.isArray(rr))rr=[];rr=rr.filter(function(x){return x.book!==book||x.chapter!==n});rr.unshift({book:book,chapter:n});localStorage.setItem(RECENT,JSON.stringify(rr.slice(0,8)))}catch(e){}refreshContinue();id('bibleBrowser').classList.add('hide');id('bibleChapterView').classList.add('hide');id('bibleReaderView').classList.remove('hide');id('bibleReaderTitle').textContent=book+' '+n;setSize(size());id('biblePrevChapter').disabled=n<=1;id('bibleNextChapter').disabled=n>=count;window.scrollTo(0,0)}
function pendingOpen(){try{var raw=sessionStorage.getItem('copticDailyPrayer_bibleOpen_v1');if(!raw)return null;sessionStorage.removeItem('copticDailyPrayer_bibleOpen_v1');var x=JSON.parse(raw);return x&&x.book&&x.chapter?x:null}catch(e){return null}}
function route(){if(location.hash==='#bible'){build();var x=pendingOpen();if(x&&chapters[x.book])openChapter(x.book,Number(x.chapter))}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',route);else route();window.addEventListener('hashchange',route);
})();