(function(){
'use strict';
var selected=new Date(),month=new Date(selected.getFullYear(),selected.getMonth(),1),detail=null,loading=false;
var MONTHS=['Tout','Baba','Hathor','Kiahk','Toba','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Pi Kogi Enavot'];
function id(x){return document.getElementById(x)}
function pad(n){return n<10?'0'+n:String(n)}
function key(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
function same(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function vals(v){return !v?[]:(Array.isArray(v)?v:[v])}
function styles(){if(id('nativeCalendarStyles'))return;var s=document.createElement('style');s.id='nativeCalendarStyles';s.textContent='.calendarCard{padding:18px}.calendarTop strong{font:700 19px Georgia,serif}.calendarGrid button.selected{background:var(--wine)!important;color:#fff!important;border-radius:50%}.calendarGrid button.hasDay{cursor:pointer}.churchDayCard{padding:24px;margin-top:14px}.churchDayCard h2{font:700 30px/1.15 Georgia,serif;margin:5px 0}.churchMeta{color:var(--muted);line-height:1.5}.churchBadges{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.churchBadge{font-size:12px;font-weight:750;color:var(--wine);background:var(--soft);padding:7px 10px;border-radius:999px}.churchActions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:20px}.churchActions a,.churchActions button{min-height:50px;border-radius:16px;border:1px solid var(--line);background:#fff;color:var(--wine);font-weight:750;display:grid;place-items:center;text-decoration:none}.churchActions button:first-child{background:var(--wine);color:#fff;border-color:var(--wine)}.synaxPreview{margin-top:18px;padding-top:16px;border-top:1px solid var(--line)}.synaxPreview strong{display:block;font:700 18px Georgia,serif;margin-bottom:7px}.synaxPreview p{margin:0;color:var(--muted);line-height:1.55}.synaxSheet{position:fixed;z-index:90;left:50%;transform:translateX(-50%);bottom:0;width:min(100%,560px);max-height:88vh;overflow:auto;background:var(--paper);border-radius:28px 28px 0 0;padding:22px 20px calc(30px + env(safe-area-inset-bottom));box-shadow:0 -18px 70px rgba(30,20,14,.18)}';document.head.appendChild(s)}
function copticLabel(c){var raw=c&&(c.copticDate||c.coptic_date);if(typeof raw==='string')return raw;if(raw&&typeof raw==='object'){var m=raw.monthName||MONTHS[Number(raw.month)-1]||raw.month||'',day=raw.day||'',year=raw.year||'';return[m,day,year].filter(Boolean).join(' ')}return c&&c.date?c.date:'Coptic Church Day'}
function synList(s){var root=s&&s.data?s.data:s;var list=vals(root&&(root.entries||root.synaxarium||root));return list.filter(function(x){return x&&typeof x==='object'})}
function build(){var screen=id('calendar');if(!screen||id('nativeCalendarCard'))return;styles();screen.innerHTML='<header class="pageHead"><div class="eyebrow">Coptic Church</div><h1>Calendar</h1><p class="subtitle">Church days, commemorations, fasting, and the Synaxarium.</p></header><article class="calendarCard" id="nativeCalendarCard"></article><article class="quietCard churchDayCard" id="nativeChurchDay"><p class="churchMeta">Select a day to view the Church calendar.</p></article>'}
function renderMonth(){build();var card=id('nativeCalendarCard');if(!card)return;var first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0),today=new Date(),cells='',i,d;for(i=0;i<first.getDay();i++)cells+='<button disabled></button>';for(d=1;d<=last.getDate();d++){var dt=new Date(month.getFullYear(),month.getMonth(),d);cells+='<button class="hasDay '+(same(dt,today)?'today ':'')+(same(dt,selected)?'selected':'')+'" data-day="'+d+'">'+d+'</button>'}card.innerHTML='<div class="calendarTop"><button id="nativeCalPrev" type="button">‹</button><strong>'+month.toLocaleDateString(undefined,{month:'long',year:'numeric'})+'</strong><button id="nativeCalNext" type="button">›</button></div><div class="calendarGrid"><span>S</span><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span>'+cells+'</div>';id('nativeCalPrev').onclick=function(){month=new Date(month.getFullYear(),month.getMonth()-1,1);renderMonth()};id('nativeCalNext').onclick=function(){month=new Date(month.getFullYear(),month.getMonth()+1,1);renderMonth()};var bs=card.querySelectorAll('[data-day]');for(i=0;i<bs.length;i++)bs[i].onclick=function(){selected=new Date(month.getFullYear(),month.getMonth(),Number(this.getAttribute('data-day')));renderMonth();loadDay()}}
function renderDay(){var host=id('nativeChurchDay');if(!host)return;if(!detail){host.innerHTML='<p class="churchMeta">Loading the selected Church day…</p>';return}var c=detail.calendar||{},syn=synList(detail.synax),celebs=vals(detail.celebrations&&detail.celebrations.data?detail.celebrations.data:detail.celebrations).map(function(x){return typeof x==='string'?x:(x&&(x.name||x.title))}).filter(Boolean),fast=detail.fasting&&detail.fasting.data?detail.fasting.data:detail.fasting,badges=[],season=c.season||c.seasonName;if(season)badges.push(season);badges=badges.concat(celebs.slice(0,2));if(fast===true||(fast&&(fast.isFasting||fast.fasting)))badges.push('Fast');var first=syn[0],preview='';if(first){var text=String(first.text||'').replace(/\s+/g,' ');preview='<div class="synaxPreview"><strong>'+esc(first.name||first.title||'Synaxarium')+'</strong><p>'+esc(text.slice(0,220))+(text.length>220?'…':'')+'</p></div>'}host.innerHTML='<div class="eyebrow">Selected Church Day</div><h2>'+esc(copticLabel(c))+'</h2><div class="churchMeta">'+esc(selected.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'}))+'</div>'+(badges.length?'<div class="churchBadges">'+badges.map(function(x){return'<span class="churchBadge">'+esc(x)+'</span>'}).join('')+'</div>':'')+preview+'<div class="churchActions"><button id="nativeSynax" type="button">Read Synaxarium</button><a id="nativeDayReadings" href="#readings">View Readings</a></div>';id('nativeSynax').onclick=function(){openSynax(syn)};id('nativeDayReadings').onclick=function(){try{sessionStorage.setItem('copticDailyPrayer_selectedReadingDate',key(selected))}catch(e){}}}
function openSynax(list){if(!list.length)return;var sheet=id('nativeSynaxSheet');if(!sheet){sheet=document.createElement('div');sheet.id='nativeSynaxSheet';sheet.className='synaxSheet';document.body.appendChild(sheet)}sheet.innerHTML='<button class="sheetClose" id="nativeSynaxClose" type="button">Done</button><div class="eyebrow">Synaxarium</div><h2>'+esc(copticLabel(detail.calendar||{}))+'</h2>'+list.map(function(x){return'<article style="margin:22px 0"><h3 style="font:700 22px Georgia,serif">'+esc(x.name||x.title||'Commemoration')+'</h3><p style="font:400 18px/1.65 Georgia,serif">'+esc(x.text||'')+'</p></article>'}).join('');id('nativeSynaxClose').onclick=function(){sheet.parentNode.removeChild(sheet)}}
function get(path){return fetch('/api/church?path='+encodeURIComponent(path),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error(String(r.status));return r.json()})}
function loadDay(){if(loading)return;loading=true;detail=null;renderDay();var k=key(selected);Promise.all([get('/calendar/'+k),get('/synaxarium/'+k),get('/celebrations/'+k),get('/fasting/'+k)]).then(function(res){detail={calendar:res[0].data||res[0],synax:res[1],celebrations:res[2],fasting:res[3]};loading=false;renderDay()}).catch(function(){loading=false;var host=id('nativeChurchDay');if(host)host.innerHTML='<p class="churchMeta">This Church day could not be loaded. Please try again.</p>'})}
function route(){if(location.hash==='#calendar'){build();renderMonth();if(!detail&&!loading)loadDay()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){build();renderMonth();route()});else{build();renderMonth();route()}window.addEventListener('hashchange',route);
})();