(()=>{
let selected=new Date(),month=new Date(selected.getFullYear(),selected.getMonth(),1),detail=null;
const MONTHS=['Tout','Baba','Hathor','Kiahk','Toba','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Pi Kogi Enavot'];
const style=document.createElement('style');style.textContent=`.calendarCard{padding:18px}.calendarTop strong{font:700 19px Georgia,serif}.calendarGrid button.selected{background:var(--wine)!important;color:#fff!important;border-radius:50%}.calendarGrid button.hasDay{cursor:pointer}.churchDayCard{padding:24px;margin-top:14px}.churchDayCard h2{font:700 30px/1.15 Georgia,serif;margin:5px 0}.churchMeta{color:var(--muted);line-height:1.5}.churchBadges{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.churchBadge{font-size:12px;font-weight:750;color:var(--wine);background:var(--soft);padding:7px 10px;border-radius:999px}.churchActions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:20px}.churchActions button{min-height:50px;border-radius:16px;border:1px solid var(--line);background:#fff;color:var(--wine);font-weight:750}.churchActions button:first-child{background:var(--wine);color:#fff;border-color:var(--wine)}.synaxPreview{margin-top:18px;padding-top:16px;border-top:1px solid var(--line)}.synaxPreview strong{display:block;font:700 18px Georgia,serif;margin-bottom:7px}.synaxPreview p{margin:0;color:var(--muted);line-height:1.55}`;document.head.appendChild(style);
function key(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function same(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function values(v){return !v?[]:Array.isArray(v)?v:[v]}
function copticLabel(c){const raw=c?.copticDate||c?.coptic_date;if(typeof raw==='string')return raw;if(raw&&typeof raw==='object'){const m=raw.monthName||MONTHS[Number(raw.month)-1]||raw.month||'',day=raw.day||'',year=raw.year||'';return [m,day,year].filter(Boolean).join(' ')}return c?.date||'Coptic Church Day'}
function renderMonth(){const card=document.querySelector('[data-screen="calendar"] .calendarCard');if(!card)return;const first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0),offset=first.getDay(),today=new Date();let cells='';for(let i=0;i<offset;i++)cells+='<button disabled></button>';for(let d=1;d<=last.getDate();d++){const dt=new Date(month.getFullYear(),month.getMonth(),d);cells+=`<button class="hasDay ${same(dt,today)?'today':''} ${same(dt,selected)?'selected':''}" data-day="${d}">${d}</button>`}card.innerHTML=`<div class="calendarTop"><button id="calPrev">‹</button><strong>${new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(month)}</strong><button id="calNext">›</button></div><div class="calendarGrid"><span>S</span><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span>${cells}</div>`;document.getElementById('calPrev').onclick=()=>shiftMonth(-1);document.getElementById('calNext').onclick=()=>shiftMonth(1);card.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>selectDay(Number(b.dataset.day)))}
function shiftMonth(n){month=new Date(month.getFullYear(),month.getMonth()+n,1);renderMonth()}
function selectDay(day){selected=new Date(month.getFullYear(),month.getMonth(),day);renderMonth();loadDay()}
function normalizeSynax(s){const root=s?.data||s;const list=values(root?.entries||root?.synaxarium||root);return list.filter(x=>x&&typeof x==='object')}
function openReadings(){const dateKey=key(selected);sessionStorage.setItem('copticDailyPrayer_selectedReadingDate',dateKey);document.querySelector('[data-target="readings"]')?.click()}
function authoritativeFallback(){const dow=selected.getDay(),m=selected.getMonth()+1,d=selected.getDate(),y=selected.getFullYear();let season='';const nayrouzStart=new Date(y,8,(y%4===3)?12:11),crossStart=new Date(y,8,(y%4===3)?28:27);if(selected>=nayrouzStart&&selected<crossStart)season='Nayrouz Season';const weeklyFast=dow===3||dow===5;return{season,weeklyFast}}
function renderDay(){let host=document.getElementById('shellCalendarDay');if(!host){host=document.createElement('article');host.id='shellCalendarDay';host.className='quietCard churchDayCard';document.querySelector('[data-screen="calendar"] .calendarCard').after(host)}if(!detail){host.innerHTML='<p class="churchMeta">Loading the selected Church day…</p>';return}const c=detail.calendar||{},syn=normalizeSynax(detail.synax),celebs=values(detail.celebrations?.data||detail.celebrations).map(x=>typeof x==='string'?x:x?.name||x?.title).filter(Boolean),fast=detail.fasting?.data||detail.fasting;const fallback=authoritativeFallback(),apiFast=fast===true||fast?.isFasting||fast?.fasting,seasonText=String(c.season||c.seasonName||'').toLowerCase(),celebrationText=celebs.join(' ').toLowerCase(),holyFifty=/holy fifty|pentecost/.test(seasonText),majorFeast=/nativity|theophany|resurrection|ascension|pentecost/.test(celebrationText),weeklyFast=fallback.weeklyFast&&!holyFifty&&!majorFeast,fasting=apiFast||weeklyFast,badges=[c.season||c.seasonName||fallback.season,...celebs.slice(0,2),fasting?'Fasting Day':''].filter(Boolean);const firstSyn=syn[0];host.innerHTML=`<div class="eyebrow">Selected Church Day</div><h2>${esc(copticLabel(c))}</h2><div class="churchMeta">${esc(new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(selected))}</div><div class="sourceNote">Primary reference for fasting/feast safeguards: Southern United States Coptic Orthodox Diocese (SUSCopts). Daily Church data is loaded from the app’s Church-data service.</div>${badges.length?`<div class="churchBadges">${badges.map(x=>`<span class="churchBadge">${esc(x)}</span>`).join('')}</div>`:''}${firstSyn?`<div class="synaxPreview"><strong>${esc(firstSyn.name||firstSyn.title||'Synaxarium')}</strong><p>${esc(String(firstSyn.text||'').replace(/\s+/g,' ').slice(0,220))}${String(firstSyn.text||'').length>220?'…':''}</p></div>`:''}<div class="churchActions"><button id="viewSynax">Read Synaxarium</button><button id="viewDayReadings">View Readings</button></div>`;document.getElementById('viewDayReadings').onclick=openReadings;document.getElementById('viewSynax').onclick=()=>openSynax(syn)}
function openSynax(list){if(!list.length)return;let sheet=document.getElementById('synaxSheet');if(!sheet){sheet=document.createElement('div');sheet.id='synaxSheet';sheet.className='prayerSheet hide';document.body.appendChild(sheet)}sheet.innerHTML=`<button class="sheetClose" id="synaxClose">Done</button><div class="eyebrow">Synaxarium</div><h2>${esc(copticLabel(detail.calendar||{}))}</h2>${list.map(x=>`<article style="margin:22px 0"><h3 style="font:700 22px Georgia,serif">${esc(x.name||x.title||'Commemoration')}</h3><p style="font:400 18px/1.65 Georgia,serif">${esc(x.text||'')}</p></article>`).join('')}`;sheet.classList.remove('hide');document.getElementById('synaxClose').onclick=()=>sheet.classList.add('hide')}
async function loadDay(){detail=null;renderDay();const k=key(selected);try{const paths=['/calendar/'+k,'/synaxarium/'+k,'/celebrations/'+k,'/fasting/'+k],res=await Promise.all(paths.map(p=>fetch('/api/church?path='+encodeURIComponent(p)).then(r=>r.json())));detail={calendar:res[0].data||res[0],synax:res[1],celebrations:res[2],fasting:res[3]};renderDay()}catch(e){const host=document.getElementById('shellCalendarDay');if(host)host.innerHTML='<p class="churchMeta">This Church day could not be loaded. Please try again.</p>';console.error(e)}}
function boot(){renderMonth();loadDay()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();