(function(){
'use strict';
var selected=new Date(),month=new Date(selected.getFullYear(),selected.getMonth(),1),detail=null,loading=false,INTER='copticDailyPrayer_intercessors_v1';
var MONTHS=['Tout','Baba','Hathor','Kiahk','Toba','Meshir','Paremhat','Parmouti','Pashons','Paoni','Epip','Mesori','Pi Kogi Enavot'];
function id(x){return document.getElementById(x)}function pad(n){return n<10?'0'+n:String(n)}function key(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}function same(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}function vals(v){return !v?[]:(Array.isArray(v)?v:[v])}
function styles(){if(id('nativeCalendarStyles'))return;var s=document.createElement('style');s.id='nativeCalendarStyles';s.textContent='.calendarCard{padding:18px}.calendarTop strong{font:700 19px Georgia,serif}.calendarGrid button.today{box-shadow:inset 0 0 0 1.5px var(--wine);border-radius:50%;color:var(--wine)}.calendarGrid button.selected{background:var(--wine)!important;color:#fff!important;border-radius:50%;box-shadow:none}.calendarGrid button.hasDay{cursor:pointer}.churchDayCard{padding:24px;margin-top:14px}.churchDayCard h2{font:700 30px/1.15 Georgia,serif;margin:5px 0}.churchMeta{color:var(--muted);line-height:1.5}.churchBadges{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.churchBadge{font-size:12px;font-weight:750;color:var(--wine);background:var(--soft);padding:7px 10px;border-radius:999px}.churchActions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:20px}.churchActions a,.churchActions button{min-height:50px;border-radius:16px;border:1px solid var(--line);background:#fff;color:var(--wine);font-weight:750;display:grid;place-items:center;text-decoration:none}.churchActions button:first-child{background:var(--wine);color:#fff;border-color:var(--wine)}.synaxPreview{margin-top:18px;padding-top:16px;border-top:1px solid var(--line)}.synaxPreview strong{display:block;font:700 18px Georgia,serif;margin-bottom:7px}.synaxPreview p{margin:0;color:var(--muted);line-height:1.55}.synaxSheet{position:fixed;z-index:90;left:50%;transform:translateX(-50%);bottom:0;width:min(100%,560px);max-height:88vh;overflow:auto;background:var(--paper);border-radius:28px 28px 0 0;padding:22px 20px calc(30px + env(safe-area-inset-bottom));box-shadow:0 -18px 70px rgba(30,20,14,.18)}.synaxSaint{margin:22px 0;padding-bottom:22px;border-bottom:1px solid var(--line)}.synaxSaint:last-child{border-bottom:0}.saintAdd{margin-top:12px;min-height:44px;padding:0 13px;border:1px solid var(--line);border-radius:14px;background:#fff;color:var(--wine);font-weight:750}.saintAdd.saved{background:var(--soft)}';document.head.appendChild(s)}
function seasonName(c){var s=c&&(c.seasonName||c.season||c.liturgicalSeason||c.liturgical_season);if(s&&typeof s==='object')s=s.name||s.title||s.description||'';return String(s||'')}function seasonValue(s,c){s=s&&s.data?s.data:s||{};var v=s.name||s.title||s.seasonName||s.season||s.liturgicalSeason||s.liturgical_season;if(v&&typeof v==='object')v=v.name||v.title||v.description||'';return String(v||seasonName(c)||'')}
function fastValue(f){f=f&&f.data?f.data:f||{};var v=typeof f==='boolean'?f:f.isFasting;if(v===undefined&&f&&typeof f==='object')v=f.isFast!==undefined?f.isFast:f.fasting;if(v&&typeof v==='object')v=v.isFasting!==undefined?v.isFasting:v.value;if(typeof v==='string'){v=v.toLowerCase();if(v==='true'||v==='yes'||v==='fasting')return true;if(v==='false'||v==='no'||v==='not fasting')return false}return v===true?true:(v===false?false:null)}
function suscoptsFast2026(d){
 var k=key(d),dow=d.getDay(),inRange=function(a,b){return k>=a&&k<=b};
 var major={'2026-01-07':1,'2026-01-19':1,'2026-04-12':1,'2026-05-21':1,'2026-05-31':1,'2026-06-01':1};
 if(major[k])return false;
 if(inRange('2026-04-12','2026-05-31'))return false;
 if(inRange('2026-02-02','2026-02-04'))return true;
 if(inRange('2026-02-16','2026-04-11'))return true;
 if(inRange('2026-06-01','2026-07-11'))return true;
 if(inRange('2026-08-07','2026-08-21'))return true;
 if(inRange('2026-11-25','2026-12-31'))return true;
 if(inRange('2026-01-01','2026-01-06'))return true;
 return dow===3||dow===5
}
function safeFastValue(raw,s,c,d){if(d.getFullYear()===2026)return suscoptsFast2026(d);var api=fastValue(raw);if(d.getDay()===3||d.getDay()===5)return true;return api===true?true:null}
function copticLabel(c){c=c&&c.data?c.data:c||{};var raw=c.copticDate||c.coptic_date||c.coptic;if(!raw&&(c.dateString||c.monthString||c.day||c.year))raw=c;if(typeof raw==='string')return raw;if(raw&&typeof raw==='object'){if(raw.dateString)return raw.dateString;var m=raw.monthString||raw.monthName||raw.month_name||MONTHS[Number(raw.month)-1]||raw.month||'',day=raw.day||raw.dayOfMonth||raw.day_of_month||'',year=raw.year||'';return[m,day,year].filter(Boolean).join(' ')}var m=c.copticMonthName||c.coptic_month_name||'',d=c.copticDay||c.coptic_day||'',y=c.copticYear||c.coptic_year||'';if(m||d||y)return[m,d,y].filter(Boolean).join(' ');return'Coptic Church Day'}
function copticParts(c){c=c&&c.data?c.data:c||{};var x=c.copticDate||c.coptic_date||c.coptic||((c.dateString||c.monthString||c.day||c.year)?c:{});return typeof x==='object'?x:{}}
function displaySeason(raw,c){var p=copticParts(c),n=String(raw||'').trim(),m=String(p.monthString||'').toLowerCase();if((m==='tout'||m==='thoout'||m==='thout'||m==='tute')&&Number(p.day)>=1&&Number(p.day)<=16)return'Nayrouz Season';if(/ordinary time/i.test(n))return'';return n}
function synList(s){var root=s&&s.data?s.data:s;if(!root)return[];var list;if(Array.isArray(root))list=root;else list=vals(root.entries||root.synaxarium||root.commemorations||root.events||root.items||root.results);return list.filter(function(x){return x&&typeof x==='object'})}
function normName(s){return String(s||'').toLowerCase().replace(/\bst\.?\b|\bsaint\b|\bpope\b|\bmartyr\b|\bthe\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ')}
function intercessors(){try{var a=JSON.parse(localStorage.getItem(INTER)||'[]');return Array.isArray(a)?a:[]}catch(e){return[]}}function isSaved(name){var a=intercessors();for(var i=0;i<a.length;i++)if(normName(a[i].name)===normName(name))return true;return false}
function addSaint(x){var name=x.name||x.title||x.heading||'Commemoration',text=String(x.text||x.description||x.content||x.story||'').replace(/\s+/g,' ').trim(),a=intercessors();for(var i=0;i<a.length;i++)if(normName(a[i].name)===normName(name))return false;a.push({name:name,summary:text.slice(0,700),date:key(selected),dateLabel:copticLabel(detail&&detail.calendar?detail.calendar:{}),source:'Synaxarium via Coptic.io',addedAt:(new Date()).toISOString(),reason:''});try{localStorage.setItem(INTER,JSON.stringify(a));window.dispatchEvent(new CustomEvent('coptic-intercessors-change'))}catch(e){}return true}
function build(){var screen=id('calendar');if(!screen||id('nativeCalendarCard'))return;styles();screen.innerHTML='<header class="pageHead"><div class="eyebrow">Coptic Church</div><h1>Calendar</h1><p class="subtitle">Church days, commemorations, fasting, and the Synaxarium.</p></header><article class="calendarCard" id="nativeCalendarCard"></article><article class="quietCard churchDayCard" id="nativeChurchDay"><p class="churchMeta">Select a day to view the Church calendar.</p></article>'}
function renderMonth(){build();var card=id('nativeCalendarCard');if(!card)return;var first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0),today=new Date(),cells='',i,d;for(i=0;i<first.getDay();i++)cells+='<button disabled></button>';for(d=1;d<=last.getDate();d++){var dt=new Date(month.getFullYear(),month.getMonth(),d);cells+='<button class="hasDay '+(same(dt,selected)?'selected':'')+'" data-day="'+d+'">'+d+'</button>'}card.innerHTML='<div class="calendarTop"><button id="nativeCalPrev" type="button">‹</button><strong>'+month.toLocaleDateString(undefined,{month:'long',year:'numeric'})+'</strong><button id="nativeCalNext" type="button">›</button></div><div class="calendarGrid"><span>S</span><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span>'+cells+'</div>';id('nativeCalPrev').onclick=function(){month=new Date(month.getFullYear(),month.getMonth()-1,1);renderMonth()};id('nativeCalNext').onclick=function(){month=new Date(month.getFullYear(),month.getMonth()+1,1);renderMonth()};var bs=card.querySelectorAll('[data-day]');for(i=0;i<bs.length;i++)bs[i].onclick=function(){selected=new Date(month.getFullYear(),month.getMonth(),Number(this.getAttribute('data-day')));renderMonth();loadDay()}}
function renderDay(){var host=id('nativeChurchDay');if(!host)return;if(!detail){host.innerHTML='<p class="churchMeta">Loading the selected Church day…</p>';return}var c=detail.calendar||{},syn=synList(detail.synax),celebs=vals(detail.celebrations&&detail.celebrations.data?detail.celebrations.data:detail.celebrations).map(function(x){return typeof x==='string'?x:(x&&(x.name||x.title))}).filter(Boolean),fast=safeFastValue(detail.fasting,detail.season,c,selected),badges=[],season=displaySeason(seasonValue(detail.season,c),c);if(season)badges.push(season);celebs=celebs.filter(function(x){return !/ordinary time/i.test(x)&&(!/coptic new year|nayrouz/i.test(x)||season!=='Nayrouz Season')});badges=badges.concat(celebs.slice(0,2));if(fast===true)badges.push('Fasting day');var first=syn[0],preview='';if(first){var text=String(first.text||first.description||first.content||first.story||'').replace(/\s+/g,' ');preview='<div class="synaxPreview"><strong>'+esc(first.name||first.title||first.heading||'Synaxarium')+'</strong><p>'+esc(text.slice(0,220))+(text.length>220?'…':'')+'</p></div>'}host.innerHTML='<div class="eyebrow">Selected Church Day</div><h2>'+esc(copticLabel(c))+'</h2><div class="churchMeta">'+esc(selected.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'}))+'</div>'+(fast===false?'<div class="churchMeta">No fast indicated for this Church day</div>':'')+(fast===null?'<div class="churchMeta">Fasting status unavailable</div>':'')+(badges.length?'<div class="churchBadges">'+badges.map(function(x){return'<span class="churchBadge">'+esc(x)+'</span>'}).join('')+'</div>':'')+preview+'<div class="churchMeta" style="margin-top:12px">Church calendar data via Coptic.io · Fasting calendar via SUSCopts</div><div class="churchActions"><button id="nativeSynax" type="button">Read Synaxarium</button><a id="nativeDayReadings" href="#readings">View Readings</a></div>';id('nativeSynax').onclick=function(){openSelectedSynaxarium()};id('nativeDayReadings').onclick=function(){try{sessionStorage.setItem('copticDailyPrayer_selectedReadingDate',key(selected))}catch(e){}}}
function openSynax(list){if(!list.length){var host=id('nativeChurchDay');if(host){var note=document.createElement('p');note.className='churchMeta';note.textContent='No Synaxarium entry is available for this day.';host.appendChild(note)}return;}var sheet=id('nativeSynaxSheet');if(!sheet){sheet=document.createElement('div');sheet.id='nativeSynaxSheet';sheet.className='synaxSheet';document.body.appendChild(sheet)}sheet.innerHTML='<button class="sheetClose" id="nativeSynaxClose" type="button">Done</button><div class="eyebrow">Synaxarium</div><h2>'+esc(copticLabel(detail.calendar||{}))+'</h2>'+list.map(function(x,i){var n=x.name||x.title||x.heading||'Commemoration',body=x.text||x.description||x.content||x.story||'';return'<article class="synaxSaint"><h3 style="font:700 22px Georgia,serif">'+esc(n)+'</h3><p style="font:400 18px/1.65 Georgia,serif">'+esc(body)+'</p><button class="saintAdd '+(isSaved(n)?'saved':'')+'" data-saint="'+i+'" type="button">'+(isSaved(n)?'Saved to My Intercessors ✓':'Add to My Intercessors')+'</button></article>'}).join('');id('nativeSynaxClose').onclick=function(){sheet.parentNode.removeChild(sheet)};var bs=sheet.querySelectorAll('[data-saint]');for(var i=0;i<bs.length;i++)bs[i].onclick=function(){var x=list[Number(this.getAttribute('data-saint'))];if(addSaint(x)){this.textContent='Saved to My Intercessors ✓';this.className='saintAdd saved'}}}
function get(path){return fetch('/api/church?path='+encodeURIComponent(path),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error(String(r.status));return r.json()})}
function loadDay(){if(loading)return;loading=true;detail=null;renderDay();var k=key(selected);Promise.all([get('/calendar/'+k),get('/synaxarium/'+k+'?detailed=true').catch(function(){return get('/synaxarium/'+k)}),get('/celebrations/'+k).catch(function(){return{}}),get('/fasting/'+k).catch(function(){return{}}),get('/season/'+k).catch(function(){return{}})]).then(function(res){detail={calendar:res[0].data||res[0],synax:res[1],celebrations:res[2],fasting:res[3],season:res[4]};loading=false;renderDay()}).catch(function(){loading=false;var host=id('nativeChurchDay');if(host)host.innerHTML='<p class="churchMeta">This Church day could not be loaded. Please try again.</p>'})}
function restoreSynaxDate(){if(location.hash!=='#synaxarium')return;try{var k=sessionStorage.getItem('copticDailyPrayer_selectedSynaxDate')||'',p=k.split('-');if(p.length===3){var d=new Date(Number(p[0]),Number(p[1])-1,Number(p[2]));if(!isNaN(d.getTime())){selected=d;month=new Date(d.getFullYear(),d.getMonth(),1)}}}catch(e){}}
function route(){if(location.hash==='#calendar'||location.hash==='#synaxarium'){restoreSynaxDate();build();renderMonth();if(!detail&&!loading)loadDay();if(location.hash==='#synaxarium'){var tries=0,t=setInterval(function(){tries++;if(detail){clearInterval(t);openSynax(synList(detail.synax))}else if(!loading&&tries>2){clearInterval(t)}else if(tries>80)clearInterval(t)},100)}}}
function openSelectedSynaxarium(){try{sessionStorage.setItem('copticDailyPrayer_selectedSynaxDate',key(selected))}catch(e){}location.hash='#synaxarium';if(detail)openSynax(synList(detail.synax))}
window.openSelectedSynaxarium=openSelectedSynaxarium;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){build();renderMonth();route()});else{build();renderMonth();route()}window.addEventListener('hashchange',route);
})();