(function(){'use strict';
var ACTIVE='copticDailyPrayer_activePrayerHour_v1',PERIOD={first:'Morning prayer',third:'Morning prayer',sixth:'Midday prayer',ninth:'Afternoon prayer',eleventh:'Evening prayer',compline:'Before sleep',midnight:'Night prayer'},RHYTHM='copticDailyPrayer_rhythm_v1',DONE='copticDailyPrayer_completedHours_v1',JESUS='copticDailyPrayer_jesus_count_v1',JESUS_HISTORY='copticDailyPrayer_jesus_history_v1',INTER='copticDailyPrayer_intercessors_v1',NAMES={first:'First Hour (Prime)',third:'Third Hour (Terce)',sixth:'Sixth Hour (Sext)',ninth:'Ninth Hour (None)',eleventh:'Eleventh Hour (Vespers)',compline:'Twelfth Hour (Compline)',midnight:'Midnight Prayer'};
function q(s){return document.querySelector(s)}function qa(s){return document.querySelectorAll(s)}function pad(n){return n<10?'0'+n:String(n)}function key(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}function get(path){return fetch('/api/church?path='+encodeURIComponent(path),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error(String(r.status));return r.json()})}function data(x){return x&&x.data?x.data:x}function arr(v){return !v?[]:(Array.isArray(v)?v:[v])}

var FATHER_QUOTES=[
{text:'If we want to understand those who wrote about God, we must begin by washing and cleansing our souls.',author:'St. Athanasius the Apostolic',source:'From your quote collection'},
{text:'It does not become of us to be agitated because of the trials that befall us...but we should the more please God through these things.',author:'St. Athanasius the Apostolic',source:'From your quote collection'},
{text:'The Lord did not come to make a display. He came to heal and to teach suffering men.',author:'St. Athanasius the Apostolic',source:'On the Incarnation'},
{text:'One who knows oneself, knows God: and one who knows God is worthy to worship Him as is right.',author:'St. Anthony the Great',source:'From your quote collection'},
{text:'Always have the fear of God before your eyes. Remember Him who gives death and lives.',author:'St. Anthony the Great',source:'From your quote collection'},
{text:'The fruits of the earth are not brought to perfection immediately, but by time, rain and care; similarly, the fruits of men ripen through ascetic practice, time, perseverance, self control and patience.',author:'St. Anthony the Great',source:'From your quote collection'},
{text:'He who sits in solitude and is quiet hath escaped from three wars: hearing, speaking, seeing; yet against one thing shall he continually battle: that is, his own heart.',author:'St. Anthony the Great',source:'From your quote collection'},
{text:'For the wisdom that comes from above, from God, is an incomparable blessing.',author:'St. Cyril of Alexandria',source:'Commentary on Luke, Homily 133'},
{text:'Christians are an army without weapons, war, bloodshed, anger, or defilement.',author:'St. Clement of Alexandria',source:'From your quote collection'},
{text:'The rule of life for a perfect person is to be in the image and likeness of God.',author:'St. Clement of Alexandria',source:'From your quote collection'},
{text:'Let your afflictions be books to admonish and teach you.',author:'St. Ephrem the Syrian',source:'From your quote collection'},
{text:'Blessed is he who forces himself to perform all manner of good deeds, for the forceful shall capture the kingdom of heaven.',author:'St. Ephrem the Syrian',source:'From your quote collection'},
{text:'Love is not puffed up... arrogance is like a very tall but rotten tree.',author:'St. Ephrem the Syrian',source:'From your quote collection'},
{text:'Let them push you, but do not push; Let them crucify you, but do not crucify. Let them insult, but do not insult.',author:'St. Isaac the Syrian',source:'From your quote collection'},
{text:'If God is slow in answering your request, or if you ask but do not promptly receive anything, do not be upset, for you are not wiser than God.',author:'St. Isaac the Syrian',source:'Wisdom of St. Isaac of Nineveh'},
{text:'Abstinence of the tongue is better than abstinence of the mouth; and abstinence of the heart is better than both.',author:'St. Isaac the Syrian',source:'From your quote collection'},
{text:'The soul that loves God has its rest in God and in God alone.',author:'St. Isaac the Syrian',source:'From your quote collection'},
{text:'Do no harm to anyone, do not put confidence in him who does wrong to his neighbor, do not rejoice with him who injures his neighbor.',author:'St. Moses the Strong',source:'From your quote collection'},
{text:'Love prayer at all time so that God enlightens your heart.',author:'St. Moses the Strong',source:'From your quote collection'},
{text:'He who endures injustice for the sake of the Lord is considered a martyr.',author:'St. Moses the Strong',source:'From your quote collection'},
{text:'My beloved, we ought to strive with everything we could in tears before our Lord to have mercy on us with his tenderness and compassion.',author:'St. Moses the Black',source:'From your quote collection'},
{text:'It is patience that reveals every grace to you, and it is through patience that the saints received all that was promised to them.',author:'St. Pachomius',source:'From your quote collection'},
{text:'Brethren, if we want to escape God’s punishment and find mercy in His eyes, let us sit every evening alone by ourselves and search our souls.',author:'St. Shenouda the Archimandrite',source:'Coptic Orthodox Book of Pascha'},
{text:'If you have nothing to give people, give them a warm smile and a kind word, give them love, give them tenderness, give them a word of encouragement; give them your heart.',author:'H.H. Pope Shenouda III',source:'From your quote collection'},
{text:'But God is the All in All for us. He is our Aim for Whom we were created.',author:'H.H. Pope Shenouda III',source:'From your quote collection'},
{text:'When you examine yourself, beware of searching for excuses and justifications to cover your sins.',author:'H.H. Pope Shenouda III',source:'From your quote collection'},
{text:'There are three on which hang the spiritual life: you learn, you do, and you teach.',author:'H.H. Pope Shenouda III',source:'From your quote collection'},
{text:'Believe me, my brethren, if we really believed that God continually gives, the whole of life itself would not suffice to thank Him!',author:'H.H. Pope Shenouda III',source:'From your quote collection'},
{text:'Your love for the Lord is reflected in your prayer, and your prayer reflects your love for the Lord.',author:'St. Pope Kyrillos VI',source:'From your quote collection'},
{text:'I prayed for a pure heart, it took me a long time and a hard struggle to discover that prayer itself is the only road to a pure heart.',author:'St. Pope Kyrillos VI',source:'From your quote collection'},
{text:'Do not think for a day that your sins are greater than the mercies of God.',author:'St. Pope Kyrillos VI',source:'From your quote collection'},
{text:'A dog is better than I am, for he has love and does not judge.',author:'St. Xanthias',source:'Sayings of the Desert Fathers'},
{text:'I have often repented of having spoken but never of been silent.',author:'Abba Arsenius',source:'From your quote collection'},
{text:'Teach your heart to follow what your tongue is saying to others.',author:'Abba Poemen',source:'From your quote collection'}
];
var FATHER_BAG='copticDailyPrayer_fatherQuoteBag_v2',fatherLast=-1;
function quoteText(x){return '“'+String(x||'').replace(/^[“"']+|[”"']+$/g,'')+'”'}
function nextFatherIndex(){
 var n=FATHER_QUOTES.length,bag=[];
 try{bag=JSON.parse(sessionStorage.getItem(FATHER_BAG)||'[]')}catch(e){}
 if(!Array.isArray(bag)||!bag.length){
   for(var j=0;j<n;j++)bag.push(j);
   for(var k=bag.length-1;k>0;k--){var p=Math.floor(Math.random()*(k+1)),tmp=bag[k];bag[k]=bag[p];bag[p]=tmp}
   if(n>1&&bag[0]===fatherLast){tmp=bag[0];bag[0]=bag[1];bag[1]=tmp}
 }
 var i=bag.shift();try{sessionStorage.setItem(FATHER_BAG,JSON.stringify(bag))}catch(e){}return i
}
function showFatherQuote(){var t=q('#fatherQuoteText'),a=q('#fatherQuoteAuthor'),s=q('#fatherQuoteSource');if(!t||!a||!s)return;var i=nextFatherIndex();fatherLast=i;t.textContent=quoteText(FATHER_QUOTES[i].text);a.textContent=FATHER_QUOTES[i].author;s.textContent=FATHER_QUOTES[i].source}
function fatherQuotes(){showFatherQuote();var b=q('#fatherAnotherQuote');if(b)b.onclick=showFatherQuote}
function suggested(){var h=(new Date()).getHours();if(h<9)return['first','Morning prayer'];if(h<12)return['third','Morning prayer'];if(h<15)return['sixth','Midday prayer'];if(h<18)return['ninth','Afternoon prayer'];if(h<21)return['eleventh','Evening prayer'];return['compline','Before sleep']}
function active(){try{var h=localStorage.getItem(ACTIVE),d=new Date(),dk=key(d);if(NAMES[h]){var n=Number(localStorage.getItem('agpeya_'+dk+'_'+h+'_step')||0);return[h,n]}}catch(e){}return null}
function completedToday(h){var d=completions();return !!d[h]}function prayerHero(){var a=active(),s=suggested();if(a&&completedToday(a[0]))a=null;var h=a?a[0]:s[0],title=q('#home .heroCopy h2'),sub=q('#home .heroCopy p'),ey=q('#home .heroCopy .eyebrow'),primary=q('#home .hero .primary');if(title)title.textContent=NAMES[h].replace(/ \([^)]*\)$/,'');if(a){if(ey)ey.textContent='Continue your prayer';if(sub)sub.textContent='Section '+(a[1]+1)+' · '+PERIOD[h];if(primary)primary.textContent='Continue Prayer'}else{if(ey)ey.textContent='Your next prayer';if(sub)sub.textContent=PERIOD[h];if(primary)primary.textContent='Begin Prayer'}}
function rhythmData(){try{var x=JSON.parse(localStorage.getItem(RHYTHM)||'{}');return x.date===key(new Date())?x:{date:key(new Date()),morning:false,jesus:false,evening:false,reading:false}}catch(e){return{date:key(new Date()),morning:false,jesus:false,evening:false,reading:false}}}function saveRhythm(x){try{localStorage.setItem(RHYTHM,JSON.stringify(x))}catch(e){}}
function completions(){try{var x=JSON.parse(localStorage.getItem(DONE)||'{}');return x.date===key(new Date())&&x.hours?x.hours:{}}catch(e){return{}}}
function readingDoneToday(){try{var p='copticDailyPrayer_reading_'+key(new Date())+'_',n=0;for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf(p)===0&&localStorage.getItem(k)==='1')n++}return n>0}catch(e){return false}}
function rhythm(){var rows=qa('#home .rhythmRow'),r=rhythmData(),done=completions(),names=['morning','jesus','evening'];r.morning=!!(done.first||done.third||done.sixth);r.evening=!!(done.ninth||done.eleventh||done.compline||done.midnight);r.reading=readingDoneToday();try{var jh=JSON.parse(localStorage.getItem(JESUS_HISTORY)||'{}');r.jesus=Number(jh[key(new Date())]||0)>0}catch(e){}saveRhythm(r);for(var i=0;i<rows.length&&i<3;i++){rows[i].setAttribute('data-rhythm',names[i]);rows[i].setAttribute('role','button');rows[i].setAttribute('tabindex','0');var mark=rows[i].lastElementChild;if(mark)mark.textContent=r[names[i]]?'✓':'○';rows[i].onclick=function(){var type=this.getAttribute('data-rhythm');if(type==='jesus'){location.hash='#more';setTimeout(function(){var b=document.getElementById('lifeJesus');if(b)b.click()},80);return}location.hash='#prayer'};rows[i].onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();this.click()}}}var word=q('#home .wordSource');if(word&&r.reading&&word.textContent.indexOf('Read ✓')<0)word.textContent=word.textContent+' · Read ✓'}
function coptic(c){c=data(c)||{};var x=c.copticDate||c.coptic_date;if(typeof x==='string')return x;if(x&&typeof x==='object')return[x.monthName||x.month,x.day,x.year].filter(Boolean).join(' ');return c.copticDateFormatted||''}function seasonText(c){c=data(c)||{};var s=c.seasonName||c.season||c.liturgicalSeason||c.liturgical_season||'';if(s&&typeof s==='object')s=s.name||s.title||s.description||'';return String(s||'')}function fastingValue(f){f=data(f)||{};var v=f.isFasting;if(v===undefined)v=f.isFast;if(v===undefined)v=f.fasting;if(v&&typeof v==='object')v=v.isFasting!==undefined?v.isFasting:v.value;if(typeof v==='string'){var z=v.toLowerCase();if(z==='true'||z==='yes'||z==='fasting')return true;if(z==='false'||z==='no'||z==='not fasting')return false}return v}
function gospel(r){r=data(r)||{};var list=arr(r.LGospel);if(!list.length)list=arr(r.VGospel);if(!list.length)list=arr(r.MGospel);return list[0]||null}
function ref(r){if(!r)return'';var ch=r.chapters||[];if(!ch.length)return r.bookName||'';var a=ch[0],b=ch[ch.length-1],fv=a.verses&&a.verses[0]?a.verses[0].num:'',lv=b.verses&&b.verses.length?b.verses[b.verses.length-1].num:'';return(r.bookName||'')+' '+a.chapterNum+':'+fv+'-'+(a===b?'':b.chapterNum+':')+lv}
function excerpt(r){if(!r)return'';var out=[],ch=r.chapters||[];for(var i=0;i<ch.length&&out.length<2;i++){var vs=ch[i].verses||[];for(var j=0;j<vs.length&&out.length<2;j++)if(vs[j].text)out.push(vs[j].text)}return out.join(' ')}
function normName(s){return String(s||'').toLowerCase().replace(/\bst\.?\b/g,'saint').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}function synEntries(x){x=data(x)||x||{};var a=arr(x.entries||x.synaxarium||x);return a.filter(function(v){return v&&typeof v==='object'})}function homeIntercessor(syn){var saved=[];try{saved=JSON.parse(localStorage.getItem(INTER)||'[]')}catch(e){}if(!Array.isArray(saved)||!saved.length)return;var entries=synEntries(syn),match=null;outer:for(var i=0;i<saved.length;i++){var sn=normName(saved[i].name);if(!sn)continue;for(var j=0;j<entries.length;j++){var en=normName(entries[j].name||entries[j].title);if(en&&en===sn){match=saved[i];break outer}}}var old=q('#home .homeIntercessor');if(old)old.remove();if(!match)return;var card=document.createElement('a');card.className='quietCard homeIntercessor';card.href='#calendar';card.innerHTML='<div class="eyebrow">One of your intercessors</div><strong style="display:block;margin:5px 0">Today the Church commemorates '+match.name+'</strong><span>Read Synaxarium →</span>';var word=q('#home .wordHomeCard');if(word&&word.parentNode)word.parentNode.insertBefore(card,word.nextSibling)}
function apply(){prayerHero();var d=new Date(),k=key(d);Promise.all([get('/calendar/'+k),get('/readings/'+k+'?detailed=true'),get('/fasting/'+k),get('/synaxarium/'+k),get('/season/'+k).catch(function(){return{}})]).then(function(res){var cal=data(res[0])||{},g=gospel(res[1]),fast=data(res[2])||{},day=q('#home .churchCopticDate'),seasonEl=q('#home .churchSeason'),fastEl=q('#home .churchFast'),word=q('#home .wordExcerpt'),source=q('#home .wordSource'),ct=coptic(cal),season=seasonText(res[4])||seasonText(cal),isFast=fastingValue(fast);if(day){day.textContent=ct||'Today in the Church';day.setAttribute('aria-label',ct?'Coptic date '+ct:'Today in the Church')}if(seasonEl){seasonEl.textContent=season||'';seasonEl.hidden=!season}if(fastEl){fastEl.textContent=isFast===true?'Fasting day':(isFast===false?'Not a fasting day':'');fastEl.hidden=isFast!==true&&isFast!==false}if(word&&g){var t=excerpt(g);word.textContent=t||'Today’s Gospel'}if(source&&g)source.textContent=ref(g);homeIntercessor(res[3]);rhythm()}).catch(function(){rhythm()})}
function hourPicker(){var link=q('#home .textAction'),hero=q('#home .homeAgpeya');if(!link||!hero||q('#home .homeHours'))return;link.onclick=function(e){e.preventDefault();var box=q('#home .homeHours');if(box){box.remove();link.textContent='View all hours';return}box=document.createElement('div');box.className='homeHours';Object.keys(NAMES).forEach(function(k){var a=document.createElement('a');a.href='#prayer';var isDone=completedToday(k),cur=active(),isCurrent=cur&&cur[0]===k&&!isDone;a.innerHTML='<span>'+NAMES[k].replace(/ \([^)]*\)$/,'')+'</span>'+(isDone?'<small>Done ✓</small>':(isCurrent?'<small>Continue</small>':'<small>›</small>'));if(isDone)a.setAttribute('aria-label',NAMES[k]+' completed today');if(isCurrent)a.setAttribute('aria-label','Continue '+NAMES[k]);a.onclick=function(){try{localStorage.setItem(ACTIVE,k)}catch(e){}};box.appendChild(a)});hero.appendChild(box);link.textContent='Hide hours'}}function route(){if(!location.hash||location.hash==='#home'){apply();hourPicker();fatherQuotes()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',route);else route();window.addEventListener('hashchange',route);window.addEventListener('coptic-prayer-progress',function(){if(!location.hash||location.hash==='#home')prayerHero()});window.addEventListener('coptic-prayer-complete',function(){if(!location.hash||location.hash==='#home')rhythm()});window.addEventListener('coptic-reading-progress',function(){if(!location.hash||location.hash==='#home')rhythm()});
})();