(function(){'use strict';
var ACTIVE='copticDailyPrayer_activePrayerHour_v1',RHYTHM='copticDailyPrayer_rhythm_v1',DONE='copticDailyPrayer_completedHours_v1',JESUS='copticDailyPrayer_jesus_count_v1',JESUS_HISTORY='copticDailyPrayer_jesus_history_v1',INTER='copticDailyPrayer_intercessors_v1',NAMES={first:'First Hour (Prime)',third:'Third Hour (Terce)',sixth:'Sixth Hour (Sext)',ninth:'Ninth Hour (None)',eleventh:'Eleventh Hour (Vespers)',compline:'Twelfth Hour (Compline)',midnight:'Midnight Prayer'};
function q(s){return document.querySelector(s)}function qa(s){return document.querySelectorAll(s)}function pad(n){return n<10?'0'+n:String(n)}function key(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}function get(path){return fetch('/api/church?path='+encodeURIComponent(path),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error(String(r.status));return r.json()})}function data(x){return x&&x.data?x.data:x}function arr(v){return !v?[]:(Array.isArray(v)?v:[v])}
function suggested(){var h=(new Date()).getHours();if(h<9)return['first','Morning prayer'];if(h<12)return['third','Morning prayer'];if(h<15)return['sixth','Midday prayer'];if(h<18)return['ninth','Afternoon prayer'];if(h<21)return['eleventh','Evening prayer'];return['compline','Before sleep']}
function active(){try{var h=localStorage.getItem(ACTIVE);if(NAMES[h]){var n=Number(localStorage.getItem('agpeya_'+h+'_step')||0);return[h,n]}}catch(e){}return null}
function completedToday(h){var d=completions();return !!d[h]}function prayerHero(){var a=active(),s=suggested();if(a&&completedToday(a[0]))a=null;var h=a?a[0]:s[0],title=q('#home .heroCopy h2'),sub=q('#home .heroCopy p'),ey=q('#home .heroCopy .eyebrow'),primary=q('#home .hero .primary');if(title)title.textContent=NAMES[h];if(a){if(ey)ey.textContent='Continue your prayer';if(sub)sub.textContent='Agpeya · Section '+(a[1]+1);if(primary)primary.textContent='Continue Prayer →'}else{if(ey)ey.textContent='Your next prayer';if(sub)sub.textContent='Agpeya · '+s[1];if(primary)primary.textContent='Begin Prayer →'}}
function rhythmData(){try{var x=JSON.parse(localStorage.getItem(RHYTHM)||'{}');return x.date===key(new Date())?x:{date:key(new Date()),morning:false,jesus:false,evening:false,reading:false}}catch(e){return{date:key(new Date()),morning:false,jesus:false,evening:false,reading:false}}}function saveRhythm(x){try{localStorage.setItem(RHYTHM,JSON.stringify(x))}catch(e){}}
function completions(){try{var x=JSON.parse(localStorage.getItem(DONE)||'{}');return x.date===key(new Date())&&x.hours?x.hours:{}}catch(e){return{}}}
function readingDoneToday(){try{var p='copticDailyPrayer_reading_'+key(new Date())+'_',n=0;for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf(p)===0&&localStorage.getItem(k)==='1')n++}return n>0}catch(e){return false}}
function rhythm(){var rows=qa('#home .rhythmRow'),r=rhythmData(),done=completions(),names=['morning','jesus','evening'];r.morning=!!(done.first||done.third||done.sixth);r.evening=!!(done.ninth||done.eleventh||done.compline||done.midnight);r.reading=readingDoneToday();try{var jh=JSON.parse(localStorage.getItem(JESUS_HISTORY)||'{}');r.jesus=Number(jh[key(new Date())]||0)>0}catch(e){}saveRhythm(r);for(var i=0;i<rows.length&&i<3;i++){rows[i].setAttribute('data-rhythm',names[i]);rows[i].setAttribute('role','button');rows[i].setAttribute('tabindex','0');var mark=rows[i].lastElementChild;if(mark)mark.textContent=r[names[i]]?'✓':'○';rows[i].onclick=function(){var type=this.getAttribute('data-rhythm');if(type==='jesus'){location.hash='#more';setTimeout(function(){var b=document.getElementById('lifeJesus');if(b)b.click()},80);return}location.hash='#prayer'};rows[i].onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();this.click()}}}var word=q('#home .wordSource');if(word&&r.reading&&word.textContent.indexOf('Read ✓')<0)word.textContent=word.textContent+' · Read ✓'}
function coptic(c){c=data(c)||{};var x=c.copticDate||c.coptic_date;if(typeof x==='string')return x;if(x&&typeof x==='object')return[x.monthName||x.month,x.day,x.year].filter(Boolean).join(' ');return c.copticDateFormatted||''}function seasonText(c){c=data(c)||{};var s=c.seasonName||c.season||c.liturgicalSeason||c.liturgical_season||'';if(s&&typeof s==='object')s=s.name||s.title||s.description||'';return String(s||'')}function fastingValue(f){f=data(f)||{};var v=f.isFasting;if(v===undefined)v=f.isFast;if(v===undefined)v=f.fasting;if(v&&typeof v==='object')v=v.isFasting!==undefined?v.isFasting:v.value;if(typeof v==='string'){var z=v.toLowerCase();if(z==='true'||z==='yes'||z==='fasting')return true;if(z==='false'||z==='no'||z==='not fasting')return false}return v}
function gospel(r){r=data(r)||{};var list=arr(r.LGospel);if(!list.length)list=arr(r.VGospel);if(!list.length)list=arr(r.MGospel);return list[0]||null}
function ref(r){if(!r)return'';var ch=r.chapters||[];if(!ch.length)return r.bookName||'';var a=ch[0],b=ch[ch.length-1],fv=a.verses&&a.verses[0]?a.verses[0].num:'',lv=b.verses&&b.verses.length?b.verses[b.verses.length-1].num:'';return(r.bookName||'')+' '+a.chapterNum+':'+fv+'-'+(a===b?'':b.chapterNum+':')+lv}
function excerpt(r){if(!r)return'';var out=[],ch=r.chapters||[];for(var i=0;i<ch.length&&out.length<2;i++){var vs=ch[i].verses||[];for(var j=0;j<vs.length&&out.length<2;j++)if(vs[j].text)out.push(vs[j].text)}return out.join(' ')}
function normName(s){return String(s||'').toLowerCase().replace(/\bst\.?\b/g,'saint').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}function synEntries(x){x=data(x)||x||{};var a=arr(x.entries||x.synaxarium||x);return a.filter(function(v){return v&&typeof v==='object'})}function homeIntercessor(syn){var saved=[];try{saved=JSON.parse(localStorage.getItem(INTER)||'[]')}catch(e){}if(!Array.isArray(saved)||!saved.length)return;var entries=synEntries(syn),match=null;outer:for(var i=0;i<saved.length;i++){var sn=normName(saved[i].name);if(!sn)continue;for(var j=0;j<entries.length;j++){var en=normName(entries[j].name||entries[j].title);if(en&&(en===sn||en.indexOf(sn)>-1||sn.indexOf(en)>-1)){match=saved[i];break outer}}}var old=q('#home .homeIntercessor');if(old)old.remove();if(!match)return;var card=document.createElement('a');card.className='quietCard homeIntercessor';card.href='#calendar';card.innerHTML='<div class="eyebrow">One of your intercessors</div><strong style="display:block;margin:5px 0">Today the Church commemorates '+match.name+'</strong><span>Read Synaxarium →</span>';var word=q('#home .wordHomeCard');if(word&&word.parentNode)word.parentNode.insertBefore(card,word.nextSibling)}
function dailyPlan(){
var old=q('#home .dailyPlanCard');if(old)old.remove();
var done=completions(),r=rhythmData(),bibleDone=!!r.bibleChapter;
var card=document.createElement('article');card.className='quietCard dailyPlanCard';
var count=(done.first?1:0)+(done.compline?1:0)+(bibleDone?1:0);
card.innerHTML='<div class="dailyPlanHead"><div><div class="eyebrow">Today</div><h3>Prayer & Reading</h3></div><strong>'+count+' of 3</strong></div>'+
'<button type="button" data-plan-hour="first"><span>'+(done.first?'✓':'○')+'</span><b>1st Hour · Prime</b><em>›</em></button>'+
'<button type="button" data-plan-hour="compline"><span>'+(done.compline?'✓':'○')+'</span><b>12th Hour · Compline</b><em>›</em></button>'+
'<button type="button" data-plan-bible="1"><span>'+(bibleDone?'✓':'○')+'</span><b>Bible · 1 Chapter</b><em>›</em></button>'+
'<p>'+(count===3?'Today’s prayer & reading complete ✓':count+' of 3 completed today')+'</p>';
var hero=q('#home .homeAgpeya');if(hero&&hero.parentNode)hero.parentNode.insertBefore(card,hero);
var hours=card.querySelectorAll('[data-plan-hour]');for(var i=0;i<hours.length;i++)hours[i].onclick=function(){try{localStorage.setItem(ACTIVE,this.getAttribute('data-plan-hour'))}catch(e){}location.hash='#prayer'};
var bb=card.querySelector('[data-plan-bible]');if(bb)bb.onclick=function(){location.href='/index.html#bible'};
}
function apply(){prayerHero();dailyPlan();var d=new Date(),k=key(d);Promise.all([get('/calendar/'+k),get('/readings/'+k+'?detailed=true'),get('/fasting/'+k),get('/synaxarium/'+k)]).then(function(res){var cal=data(res[0])||{},g=gospel(res[1]),fast=data(res[2])||{},day=q('#home .churchCopticDate'),seasonEl=q('#home .churchSeason'),fastEl=q('#home .churchFast'),word=q('#home .wordExcerpt'),source=q('#home .wordSource'),ct=coptic(cal),season=seasonText(cal),isFast=fastingValue(fast);if(day)day.textContent=ct||'Today in the Church';if(seasonEl)seasonEl.textContent=season||'';if(fastEl)fastEl.textContent=isFast===true?'Fasting day':(isFast===false?'Not a fasting day':'');if(word&&g){var t=excerpt(g);word.textContent=t||'Today’s Gospel'}if(source&&g)source.textContent=ref(g);homeIntercessor(res[3]);rhythm()}).catch(function(){rhythm()})}
function hourPicker(){var link=q('#home .textAction'),hero=q('#home .homeAgpeya');if(!link||!hero||q('#home .homeHours'))return;link.onclick=function(e){e.preventDefault();var box=q('#home .homeHours');if(box){box.remove();link.textContent='View all hours';return}box=document.createElement('div');box.className='homeHours';Object.keys(NAMES).forEach(function(k){var a=document.createElement('a');a.href='#prayer';a.textContent=NAMES[k]+(completedToday(k)?'  ✓':'');if(completedToday(k))a.setAttribute('aria-label',NAMES[k]+' completed today');a.onclick=function(){try{localStorage.setItem(ACTIVE,k)}catch(e){}};box.appendChild(a)});hero.appendChild(box);link.textContent='Hide hours ↑'}}function route(){if(!location.hash||location.hash==='#home'){apply();hourPicker()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',route);else route();window.addEventListener('hashchange',route);window.addEventListener('coptic-prayer-progress',function(){if(!location.hash||location.hash==='#home')prayerHero()});window.addEventListener('coptic-prayer-complete',function(){if(!location.hash||location.hash==='#home'){rhythm();dailyPlan()}});window.addEventListener('coptic-reading-progress',function(){if(!location.hash||location.hash==='#home')rhythm()});
})();