(function(){'use strict';
var ACTIVE='copticDailyPrayer_activePrayerHour_v1',NAMES={first:'First Hour',third:'Third Hour',sixth:'Sixth Hour',ninth:'Ninth Hour',eleventh:'Eleventh Hour',compline:'Compline',midnight:'Midnight Prayer'};
function q(s){return document.querySelector(s)}function pad(n){return n<10?'0'+n:String(n)}function key(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}function get(path){return fetch('/api/church?path='+encodeURIComponent(path),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error(String(r.status));return r.json()})}function data(x){return x&&x.data?x.data:x}function arr(v){return !v?[]:(Array.isArray(v)?v:[v])}
function suggested(){var h=(new Date()).getHours();if(h<9)return['first','Morning prayer'];if(h<12)return['third','9 AM prayer'];if(h<15)return['sixth','Noon prayer'];if(h<18)return['ninth','3 PM prayer'];if(h<21)return['eleventh','Evening prayer'];return['compline','Before sleep']}
function active(){try{var h=localStorage.getItem(ACTIVE);if(NAMES[h]){var n=Number(localStorage.getItem('agpeya_'+h+'_step')||0);return[h,n]}}catch(e){}return null}
function prayerHero(){var a=active(),s=suggested(),h=a?a[0]:s[0],title=q('#home .heroCopy h2'),sub=q('#home .heroCopy p'),ey=q('#home .heroCopy .eyebrow'),primary=q('#home .hero .primary');if(title)title.textContent=NAMES[h];if(a){if(ey)ey.textContent='Continue your prayer';if(sub)sub.textContent='Agpeya · Section '+(a[1]+1);if(primary)primary.textContent='Continue Prayer →'}else{if(ey)ey.textContent='Your next prayer';if(sub)sub.textContent='Agpeya · '+s[1];if(primary)primary.textContent='Begin Prayer →'}}
function coptic(c){c=data(c)||{};var x=c.copticDate||c.coptic_date;if(typeof x==='string')return x;if(x&&typeof x==='object')return[x.monthName||x.month,x.day,x.year].filter(Boolean).join(' ');return c.copticDateFormatted||''}
function gospel(r){r=data(r)||{};var list=arr(r.LGospel);if(!list.length)list=arr(r.VGospel);if(!list.length)list=arr(r.MGospel);return list[0]||null}
function ref(r){if(!r)return'';var ch=r.chapters||[];if(!ch.length)return r.bookName||'';var a=ch[0],b=ch[ch.length-1],fv=a.verses&&a.verses[0]?a.verses[0].num:'',lv=b.verses&&b.verses.length?b.verses[b.verses.length-1].num:'';return(r.bookName||'')+' '+a.chapterNum+':'+fv+'-'+(a===b?'':b.chapterNum+':')+lv}
function excerpt(r){if(!r)return'';var out=[],ch=r.chapters||[];for(var i=0;i<ch.length&&out.length<2;i++){var vs=ch[i].verses||[];for(var j=0;j<vs.length&&out.length<2;j++)if(vs[j].text)out.push(vs[j].text)}return out.join(' ')}
function apply(){prayerHero();var d=new Date(),k=key(d);Promise.all([get('/calendar/'+k),get('/readings/'+k+'?detailed=true')]).then(function(res){var cal=data(res[0])||{},g=gospel(res[1]),day=q('#home .churchDay'),word=q('#home .wordExcerpt'),source=q('#home .wordSource'),ct=coptic(cal),season=cal.seasonName||cal.season||'';if(day)day.textContent=[ct,season].filter(Boolean).join(' · ')||'Today in the Church';if(word&&g){var t=excerpt(g);word.textContent=t||'Today’s Gospel'}if(source&&g)source.textContent=ref(g)}).catch(function(){})}
function route(){if(!location.hash||location.hash==='#home')apply()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',route);else route();window.addEventListener('hashchange',route);window.addEventListener('coptic-prayer-progress',function(){if(!location.hash||location.hash==='#home')prayerHero()});
})();