(()=>{
const KEY='copticDailyPrayer_intercessors_v1';
const style=document.createElement('style');style.textContent=`.intercessorEmpty{padding:28px 18px;text-align:center;color:var(--muted);line-height:1.55}.intercessorList{display:grid;gap:12px}.intercessorCard{border:1px solid var(--line);border-radius:18px;padding:17px;background:#fff}.intercessorCard h3{font:700 21px/1.2 Georgia,serif;margin:0 0 7px}.intercessorCard p{margin:5px 0;color:var(--muted);line-height:1.5}.intercessorCard button{border:0;background:transparent;color:var(--wine);font-weight:750;padding:8px 0}.intercessorReason{font-size:13px}.intercessorSource{font-size:11px;color:var(--muted);margin-top:9px}.saintAdd{margin-top:12px;min-height:44px;padding:0 13px;border:1px solid var(--line);border-radius:14px;background:#fff;color:var(--wine);font-weight:750}.reasonField{width:100%;box-sizing:border-box;min-height:90px;border:1px solid var(--line);border-radius:15px;padding:12px;font:400 16px/1.45 system-ui;color:var(--ink);resize:vertical}.intercessionPrayer{font:400 22px/1.6 Georgia,serif;padding:18px;border:1px solid var(--line);border-radius:18px;background:var(--soft);margin:16px 0}`;document.head.appendChild(style);
function get(){try{return JSON.parse(localStorage.getItem(KEY))||[]}catch(e){return[]}}function save(v){localStorage.setItem(KEY,JSON.stringify(v))}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function clean(s){return String(s||'').replace(/\s+/g,' ').trim()}function idFor(name,date){return (name+'|'+date).toLowerCase().replace(/[^a-z0-9|]+/g,'-')}
function summary(text){const t=clean(text);return t.length>360?t.slice(0,357).replace(/\s+\S*$/,'')+'…':t}
function addSaint(entry){const list=get(),id=idFor(entry.name,entry.date||'');if(list.some(x=>x.id===id))return false;list.push({...entry,id,addedAt:new Date().toISOString(),reason:''});save(list);renderSummary();return true}
function promptAdd(entry,button){const added=addSaint(entry);if(button){button.textContent=added?'Added to My Intercessors':'Already in My Intercessors';button.disabled=true}}
function openCorner(){let s=document.getElementById('intercessorsSheet');if(!s){s=document.createElement('div');s.id='intercessorsSheet';s.className='prayerSheet toolSheet hide';document.body.appendChild(s)}const list=get();s.innerHTML=`<button class="sheetClose" id="intercessorsClose">Done</button><div class="eyebrow">Your Prayer Life</div><h2>My Intercessors</h2><p class="toolIntro">Keep saints from the Synaxarium especially close to your prayer life. Their life summaries come from the Synaxarium you saved them from. You can privately note why you seek their intercessions.</p>${list.length?`<div class="intercessorList">${list.map(x=>`<article class="intercessorCard"><h3>${esc(x.name)}</h3><p>${esc(x.summary||'')}</p>${x.reason?`<p class="intercessorReason"><strong>My intercession intention:</strong> ${esc(x.reason)}</p>`:''}<div class="intercessorSource">Saved from the Synaxarium · ${esc(x.dateLabel||x.date||'')}</div><button data-ask="${esc(x.id)}">Ask for Intercession</button> · <button data-edit="${esc(x.id)}">${x.reason?'Edit intention':'Add intention'}</button> · <button data-remove="${esc(x.id)}">Remove</button></article>`).join('')}</div>`:'<div class="intercessorEmpty">Your corner is empty. When a saint in the Synaxarium speaks to you, add them here.</div>'}`;s.classList.remove('hide');document.getElementById('intercessorsClose').onclick=()=>s.classList.add('hide');s.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{save(get().filter(x=>x.id!==b.dataset.remove));openCorner();renderSummary()});s.querySelectorAll('[data-ask]').forEach(b=>b.onclick=()=>openIntercession(b.dataset.ask));s.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editReason(b.dataset.edit))}
function openIntercession(id){const x=get().find(a=>a.id===id);if(!x)return;let s=document.getElementById('askIntercessionSheet');if(!s){s=document.createElement('div');s.id='askIntercessionSheet';s.className='prayerSheet toolSheet hide';document.body.appendChild(s)}s.innerHTML=`<button class="sheetClose" id="askIntercessionClose">Done</button><div class="eyebrow">My Intercessor</div><h2>${esc(x.name)}</h2><p class="toolIntro">Turn to God in prayer, asking the saint's intercession. This app does not generate a prayer or put words in your mouth.</p><div class="intercessionPrayer">O ${esc(x.name)}, pray for us before the Lord.</div>${x.reason?`<p class="intercessorReason"><strong>My private intention:</strong> ${esc(x.reason)}</p>`:''}<div class="intercessorSource">Saved from the Synaxarium · ${esc(x.dateLabel||x.date||'')}</div>`;s.classList.remove('hide');document.getElementById('askIntercessionClose').onclick=()=>s.classList.add('hide')}
function editReason(id){const list=get(),x=list.find(a=>a.id===id);if(!x)return;let s=document.getElementById('intercessionReasonSheet');if(!s){s=document.createElement('div');s.id='intercessionReasonSheet';s.className='prayerSheet toolSheet hide';document.body.appendChild(s)}s.innerHTML=`<button class="sheetClose" id="reasonClose">Done</button><div class="eyebrow">My Intercessor</div><h2>${esc(x.name)}</h2><p class="toolIntro">Add your own private note about why you seek this saint's intercessions. The app will not generate or assign an intercession reason.</p><textarea class="reasonField" id="reasonText" placeholder="My intention…">${esc(x.reason||'')}</textarea><button class="saveRule" id="reasonSave" style="margin-top:14px">Save Intention</button>`;s.classList.remove('hide');document.getElementById('reasonClose').onclick=()=>s.classList.add('hide');document.getElementById('reasonSave').onclick=()=>{x.reason=document.getElementById('reasonText').value.trim();save(list);s.classList.add('hide');openCorner()}}
function renderSummary(){const b=document.querySelector('[data-tool="intercessors"]');if(!b)return;const n=get().length;let s=b.querySelector('small');if(!s){s=document.createElement('small');s.style.cssText='display:block;color:var(--muted);font-weight:400;margin-top:3px';b.querySelector('b').after(s)}s.textContent=n?`${n} ${n===1?'saint':'saints'} saved`:'Saints close to your prayer life'}
function wireMore(){const more=document.querySelector('[data-screen="more"]');if(!more)return;let b=more.querySelector('[data-tool="intercessors"]');if(!b){const group=more.querySelector('.settingsGroup');if(!group)return;b=document.createElement('button');b.dataset.tool='intercessors';b.innerHTML='<b>My Intercessors</b><span>›</span>';group.appendChild(b)}b.onclick=openCorner;renderSummary()}
function wireSynax(){const sheet=document.getElementById('synaxSheet');if(!sheet||sheet.dataset.intercessorsWired==='1')return;sheet.dataset.intercessorsWired='1';const observer=new MutationObserver(()=>decorateSynax(sheet));observer.observe(sheet,{childList:true,subtree:true});decorateSynax(sheet)}
function decorateSynax(sheet){[...sheet.querySelectorAll('article')].forEach((a,i)=>{if(a.querySelector('.saintAdd'))return;const h=a.querySelector('h3'),p=a.querySelector('p');if(!h||!p)return;const name=clean(h.textContent);if(!name)return;const dateLabel=clean(sheet.querySelector('h2')?.textContent||'');const btn=document.createElement('button');btn.className='saintAdd';btn.type='button';btn.textContent='Add to My Intercessors';btn.onclick=()=>promptAdd({name,summary:summary(p.textContent),date:dateLabel,dateLabel,source:'Synaxarium',sourceProvider:'Church data service'},btn);a.appendChild(btn)})}
function boot(){wireMore();wireSynax();new MutationObserver(()=>{wireMore();wireSynax()}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();