(()=>{
const SIZE='copticDailyPrayer_prayerTextSize_v1';
const style=document.createElement('style');style.textContent=`.sourceList{display:grid;gap:10px}.sourceItem{display:block;text-decoration:none;border:1px solid var(--line);border-radius:17px;background:#fff;padding:15px;color:var(--ink)}.sourceItem strong{display:block;font:700 17px Georgia,serif;margin-bottom:4px}.sourceItem small{color:var(--muted);line-height:1.45}.aboutCopy{font:400 18px/1.65 Georgia,serif;color:var(--ink)}.settingBlock{padding:14px 0}.settingBlock>strong{display:block;margin-bottom:10px}.settingSizes{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.settingSizes button{min-height:50px;border:1px solid var(--line);border-radius:15px;background:#fff;color:var(--ink);font-weight:800}.settingSizes button.active{background:var(--wine);color:#fff;border-color:var(--wine)}`;document.head.appendChild(style);
function sheet(id){let s=document.getElementById(id);if(!s){s=document.createElement('div');s.id=id;s.className='prayerSheet toolSheet hide';document.body.appendChild(s)}return s}function close(id){document.getElementById(id)?.classList.add('hide')}
function openSettings(){const s=sheet('readingSettingsSheet'),current=localStorage.getItem(SIZE)||localStorage.getItem('copticDailyPrayer_shellTextSize')||'23';s.innerHTML=`<button class="sheetClose" id="settingsClose">Done</button><div class="eyebrow">Prayer Tools</div><h2>Text & Reading Settings</h2><p class="toolIntro">Choose the text size used for prayer and Scripture reading.</p><div class="settingBlock"><strong>Text size</strong><div class="settingSizes"><button data-font="20" class="${current==='20'?'active':''}">A−</button><button data-font="23" class="${current==='23'?'active':''}">A</button><button data-font="27" class="${current==='27'?'active':''}">A+</button></div></div><p class="privacyNote">Your preference is stored on this device.</p>`;s.classList.remove('hide');document.getElementById('settingsClose').onclick=()=>close('readingSettingsSheet');s.querySelectorAll('[data-font]').forEach(b=>b.onclick=()=>{const n=b.dataset.font;localStorage.setItem(SIZE,n);localStorage.setItem('copticDailyPrayer_shellTextSize',n);document.documentElement.style.setProperty('--reader-size',n+'px');document.getElementById('shellPrayerText')?.style.setProperty('font-size',n+'px');s.querySelectorAll('[data-font]').forEach(x=>x.classList.toggle('active',x===b))})}
function openSources(){const s=sheet('sourcesSheet');s.innerHTML=`<button class="sheetClose" id="sourcesClose">Done</button><div class="eyebrow">About & Sources</div><h2>Church Sources</h2><p class="toolIntro">Prayer and Church-day content should remain traceable to identifiable Coptic Orthodox sources.</p><div class="sourceList"><a class="sourceItem" href="https://coptic.io/docs" target="_blank" rel="noopener"><strong>Coptic.io</strong><small>Church calendar and lectionary data used by this app.</small></a><a class="sourceItem" href="https://copticchurch.net/synaxarium" target="_blank" rel="noopener"><strong>CopticChurch.net Synaxarium</strong><small>Coptic Orthodox Synaxarium reference.</small></a><a class="sourceItem" href="https://qa.suscopts.org/index.php?catid=81&qid=61" target="_blank" rel="noopener"><strong>Southern Diocese Q&amp;A</strong><small>Source used for the confession-frequency reference.</small></a></div>`;s.classList.remove('hide');document.getElementById('sourcesClose').onclick=()=>close('sourcesSheet')}
function openAbout(){const s=sheet('aboutSheet');s.innerHTML=`<button class="sheetClose" id="aboutClose">Done</button><div class="eyebrow">Coptic Orthodox</div><h2>About Daily Prayer</h2><div class="aboutCopy"><p>This app is being built as a quiet companion for Coptic Orthodox daily prayer: the Agpeya, the Church lectionary, the calendar, and personal prayer tools in one focused place.</p><p>Personal settings, prayer progress, counters, and confession-planning information in this preview are stored locally on this device.</p><p>The app is not a substitute for the sacramental life of the Church or the guidance of a Father of Confession.</p></div>`;s.classList.remove('hide');document.getElementById('aboutClose').onclick=()=>close('aboutSheet')}
function boot(){const more=document.querySelector('[data-screen="more"]');if(!more)return;const bs=[...more.querySelectorAll('.settingsGroup button')];bs.find(b=>b.textContent.includes('Text & Reading Settings'))?.addEventListener('click',openSettings);bs.find(b=>b.textContent.includes('Church Sources'))?.addEventListener('click',openSources);bs.find(b=>b.textContent.trim().startsWith('About'))?.addEventListener('click',openAbout);const n=localStorage.getItem(SIZE)||localStorage.getItem('copticDailyPrayer_shellTextSize');if(n)document.documentElement.style.setProperty('--reader-size',n+'px')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();