(function(){
'use strict';
var hourNames={first:'First Hour',third:'Third Hour',sixth:'Sixth Hour',ninth:'Ninth Hour',eleventh:'Eleventh Hour',compline:'Compline',midnight:'Midnight Prayer'};
var ACTIVE='copticDailyPrayer_activePrayerHour_v1',hour='first',step=0,data=null,loading=false;
function id(x){return document.getElementById(x)}
function suggested(){var h=(new Date()).getHours();if(h>=9&&h<12)return'third';if(h>=12&&h<15)return'sixth';if(h>=15&&h<17)return'ninth';if(h>=17&&h<21)return'eleventh';if(h>=21||h<5)return'compline';return'first'}
function savedHour(){try{var h=localStorage.getItem(ACTIVE);return hourNames[h]?h:''}catch(e){return''}}
function markup(){return '<header class="prayerHeader"><a class="prayerBack" href="#home">‹ Home</a><button class="prayerJump" id="nativeJump" type="button" aria-label="Prayers in this Hour"><span class="jumpIcon">☰</span><span class="jumpButtonText">Prayers</span></button><button class="prayerTools" id="nativeTools" type="button">Aa ···</button><div class="eyebrow" id="shellPrayerHour">AGPEYA</div><h1 id="shellPrayerTitle">Prayer</h1><div class="prayerStep" id="shellPrayerStep">Loading the Agpeya…</div><div class="progress"><i id="shellPrayerBar"></i></div></header><article class="prayerReading" id="shellPrayerReading"><h2 id="shellSectionTitle"></h2><div class="prayerText" id="shellPrayerText"></div></article><section class="kyrieShell hide" id="shellKyrie"><div class="eyebrow">Kyrie Eleison</div><h2>Lord, have mercy.</h2><div class="kyrieCount"><span id="shellKyrieCount">0</span><small>/ 41</small></div><button id="shellMercy" class="mercyButton" type="button">LORD, HAVE MERCY</button><div id="shellKyrieRemain" class="kyrieRemain">41 remaining</div><button id="shellKyrieReset" class="resetLink" type="button">Reset</button></section><div class="prayerControls"><button id="shellPrev" type="button">Previous</button><button class="selah" id="shellSelah" type="button">Selah</button><button id="shellNext" type="button">Next</button></div><div class="prayerSheet hide" id="shellPrayerSheet"><button class="sheetClose" id="shellSheetClose" type="button">Done</button><h2>Prayer</h2><label>Text Size</label><div class="sizeRow"><button data-size="20" type="button">A−</button><button data-size="23" type="button">A</button><button data-size="27" type="button">A+</button></div><label>Choose Hour</label><div class="hourList" id="nativeHourList"></div></div><div class="prayerSheet jumpSheet hide" id="nativeJumpSheet"><button class="sheetClose" id="nativeJumpClose" type="button">Done</button><div class="eyebrow">Current Hour</div><h2 id="nativeJumpTitle">Jump to Prayer</h2><p class="jumpHint">Choose a prayer, Psalm, Gospel, litany, absolution, or other section within this Hour.</p><div class="jumpList" id="nativeJumpList"></div></div><div class="selahShell hide" id="shellSelahOverlay"><div class="selahWord">Selah</div><button id="shellContinue" type="button">Continue in Prayer</button></div>'}
function addJumpStyles(){if(id('nativeJumpStyles'))return;var s=document.createElement('style');s.id='nativeJumpStyles';s.textContent='.prayerJump{position:absolute;right:70px;top:0;border:0;background:transparent;color:var(--wine);font-weight:750;min-height:44px;padding:0 8px;display:flex;align-items:center;gap:5px}.prayerJump .jumpIcon{font-size:18px}.prayerJump .jumpButtonText{font-size:11px}.jumpSheet{max-height:84vh}.jumpHint{color:var(--muted);font-size:12px;line-height:1.5;margin:-12px 0 16px}.jumpList{border:1px solid var(--line);border-radius:18px;overflow:hidden}.jumpList button{width:100%;min-height:58px;padding:8px 14px;border:0;border-bottom:1px solid var(--line);background:transparent;display:grid;grid-template-columns:28px 1fr 18px;gap:10px;align-items:center;text-align:left;color:var(--ink)}.jumpList button:last-child{border-bottom:0}.jumpList button.current{background:var(--soft);color:var(--wine)}.jumpNumber{font:600 12px Georgia,serif;color:var(--muted);text-align:center}.jumpName{font:600 15px/1.25 Georgia,serif}.jumpChevron{color:var(--muted);font-size:20px;text-align:right}@media(max-width:390px){.prayerJump .jumpButtonText{display:none}.prayerJump{right:58px}}';document.head.appendChild(s)}
function build(){var stage=id('nativePrayerStage');if(!stage||stage.getAttribute('data-ready'))return;stage.setAttribute('data-ready','1');addJumpStyles();stage.innerHTML=markup();var list=id('nativeHourList'),k;for(k in hourNames){if(hourNames.hasOwnProperty(k)){var b=document.createElement('button');b.type='button';b.setAttribute('data-hour',k);b.innerHTML=hourNames[k]+'<span>›</span>';b.onclick=function(){selectHour(this.getAttribute('data-hour'));id('shellPrayerSheet').classList.add('hide')};list.appendChild(b)}}id('nativeTools').onclick=function(){id('shellPrayerSheet').classList.remove('hide')};id('shellSheetClose').onclick=function(){id('shellPrayerSheet').classList.add('hide')};id('nativeJump').onclick=function(){renderJump();id('nativeJumpSheet').classList.remove('hide')};id('nativeJumpClose').onclick=function(){id('nativeJumpSheet').classList.add('hide')};id('shellPrev').onclick=function(){move(-1)};id('shellNext').onclick=function(){move(1)};id('shellSelah').onclick=function(){id('shellSelahOverlay').classList.remove('hide')};id('shellContinue').onclick=function(){id('shellSelahOverlay').classList.add('hide')};id('shellMercy').onclick=function(){setMercy(Math.min(41,mercy()+1))};id('shellKyrieReset').onclick=function(){setMercy(0)};var sizes=document.querySelectorAll('#shellPrayerSheet [data-size]');for(var i=0;i<sizes.length;i++)sizes[i].onclick=function(){id('shellPrayerText').style.fontSize=this.getAttribute('data-size')+'px';try{localStorage.setItem('copticDailyPrayer_prayerTextSize_v1',this.getAttribute('data-size'))}catch(e){}};try{var size=localStorage.getItem('copticDailyPrayer_prayerTextSize_v1');if(size)id('shellPrayerText').style.fontSize=size+'px'}catch(e){}}
function titleFor(s,i){var t=s&&s.title?String(s.title):'Prayer '+(i+1);return t.replace(/\s+/g,' ').replace(/^\s+|\s+$/g,'')}
function renderJump(){var host=id('nativeJumpList');if(!host||!data||!data[hour])return;id('nativeJumpTitle').textContent=hourNames[hour]+' Prayers';host.innerHTML='';for(var i=0;i<data[hour].length;i++){var b=document.createElement('button');b.type='button';b.setAttribute('data-jump-step',String(i));if(i===step)b.className='current';b.innerHTML='<span class="jumpNumber">'+(i+1)+'</span><span class="jumpName"></span><span class="jumpChevron">›</span>';b.querySelector('.jumpName').textContent=titleFor(data[hour][i],i);b.onclick=function(){step=Number(this.getAttribute('data-jump-step'));persist();render();id('nativeJumpSheet').classList.add('hide');window.scrollTo(0,0)};host.appendChild(b)}}
function persist(){try{localStorage.setItem(ACTIVE,hour);localStorage.setItem('agpeya_'+hour+'_step',String(step))}catch(e){}try{window.dispatchEvent(new CustomEvent('coptic-prayer-progress',{detail:{hour:hour,step:step,title:hourNames[hour]}}))}catch(e){}}
function mercyKey(){return'agpeya_'+hour+'_kyrie_'+step}function mercy(){try{return Math.max(0,Math.min(41,Number(localStorage.getItem(mercyKey())||0)))}catch(e){return 0}}function setMercy(n){try{localStorage.setItem(mercyKey(),String(n))}catch(e){}renderMercy()}function renderMercy(){var n=mercy();id('shellKyrieCount').textContent=n;id('shellKyrieRemain').textContent=(41-n)+' remaining'}
function render(){if(!data||!data[hour]||!data[hour].length)return;var list=data[hour],s=list[step]||list[0],title=String(s.title||''),kyrie=title.indexOf('41')>=0;id('shellPrayerHour').textContent=hourNames[hour];id('shellPrayerTitle').textContent=title||hourNames[hour];id('shellPrayerStep').textContent='Section '+(step+1)+' of '+list.length;id('shellPrayerBar').style.width=Math.round((step+1)/list.length*100)+'%';id('shellSectionTitle').textContent=title;id('shellPrayerText').textContent=s.text||'';id('shellKyrie').classList.toggle('hide',!kyrie);id('shellPrayerReading').classList.toggle('hide',kyrie);id('shellPrev').disabled=step===0;id('shellNext').disabled=step===list.length-1;if(kyrie)renderMercy()}
function selectHour(h){if(!data||!data[h]||!data[h].length)return;hour=h;try{step=Number(localStorage.getItem('agpeya_'+h+'_step')||0)}catch(e){step=0}if(step<0||step>=data[h].length)step=0;persist();render()}
function move(d){if(!data||!data[hour])return;step=Math.max(0,Math.min(step+d,data[hour].length-1));persist();render();window.scrollTo(0,0)}
function load(){if(loading||data)return;loading=true;build();if(typeof window.loadCanonicalAgpeya!=='function'){id('shellPrayerStep').textContent='Unable to load the Agpeya';return}window.loadCanonicalAgpeya().then(function(v){data=v;loading=false;selectHour(savedHour()||suggested())}).catch(function(){loading=false;id('shellPrayerStep').textContent='Unable to load the Agpeya';id('shellPrayerText').textContent='Please refresh and try again.'})}
function route(){if(location.hash==='#prayer')load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){build();route()});else{build();route()}window.addEventListener('hashchange',route);
})();
