(()=>{
const labels={first:'First Hour',third:'Third Hour',sixth:'Sixth Hour',ninth:'Ninth Hour',eleventh:'Eleventh Hour',compline:'Twelfth Hour (Compline)',midnight:'Midnight Prayer'},keys=Object.keys(labels);let data=null;
const style=document.createElement('style');style.textContent=`.prayerJump{position:absolute;right:70px;top:0;border:0;background:transparent;color:var(--wine);font-weight:750;min-height:44px;padding:0 8px;display:flex;align-items:center;gap:5px}.prayerJump .jumpIcon{font-size:18px}.prayerJump .jumpButtonText{font-size:11px}.jumpSheet{max-height:84vh}.jumpHint{color:var(--muted);font-size:12px;line-height:1.5;margin:-12px 0 16px}.jumpList{border:1px solid var(--line);border-radius:18px;overflow:hidden}.jumpList button{width:100%;min-height:58px;padding:8px 14px;border:0;border-bottom:1px solid var(--line);background:transparent;display:grid;grid-template-columns:28px 1fr 18px;gap:10px;align-items:center;text-align:left;color:var(--ink)}.jumpList button:last-child{border-bottom:0}.jumpList button.current{background:var(--soft);color:var(--wine)}.jumpNumber{font:600 12px Georgia,serif;color:var(--muted);text-align:center}.jumpName{font:600 15px/1.25 Georgia,serif}.jumpChevron{color:var(--muted);font-size:20px;text-align:right}@media(max-width:390px){.prayerJump .jumpButtonText{display:none}.prayerJump{right:58px}}`;document.head.appendChild(style);
function currentHour(){const shown=(document.getElementById('shellPrayerHour')?.textContent||'').trim().toLowerCase();return keys.find(k=>labels[k].toLowerCase()===shown)||'first'}
function titleFor(s,i){return String(s?.title||`Prayer ${i+1}`).replace(/\s+/g,' ').trim()}
async function getData(){if(data)return data;data=await window.loadCanonicalAgpeya();return data}
function ensureUI(){const header=document.querySelector('.prayerHeader');if(!header||document.getElementById('shellJumpButton'))return;const tools=header.querySelector('.prayerTools'),jump=document.createElement('button');jump.id='shellJumpButton';jump.className='prayerJump';jump.type='button';jump.setAttribute('aria-label','Within this Hour');jump.innerHTML='<span class="jumpIcon" aria-hidden="true">☰</span><span class="jumpButtonText">Within Hour</span>';tools?header.insertBefore(jump,tools):header.appendChild(jump);const sheet=document.createElement('div');sheet.id='shellJumpSheet';sheet.className='prayerSheet jumpSheet hide';sheet.innerHTML='<button class="sheetClose" id="shellJumpClose">Done</button><div class="eyebrow">Current Hour</div><h2 id="shellJumpTitle">Within Hour</h2><p class="jumpHint">Choose a prayer, Psalm, Gospel, litany, absolution, or other section within this Hour.</p><div class="jumpList" id="shellJumpList"></div>';document.body.appendChild(sheet);jump.onclick=async()=>{sheet.classList.remove('hide');await renderList()};sheet.querySelector('#shellJumpClose').onclick=()=>sheet.classList.add('hide')}
async function renderList(){const hour=currentHour(),host=document.getElementById('shellJumpList');if(!host)return;document.getElementById('shellJumpTitle').textContent=labels[hour]+' Prayers';host.innerHTML='<p class="jumpHint" style="padding:16px;margin:0">Loading prayers…</p>';try{const all=await getData(),list=all?.[hour]||[],step=Number(localStorage.getItem('agpeya_'+hour+'_step')||0);host.innerHTML=list.map((s,i)=>`<button type="button" data-jump-step="${i}" class="${i===step?'current':''}"><span class="jumpNumber">${i+1}</span><span class="jumpName">${titleFor(s,i)}</span><span class="jumpChevron">›</span></button>`).join('');const current=host.querySelector('.current');if(current)setTimeout(()=>current.scrollIntoView({block:'center'}),0);host.querySelectorAll('[data-jump-step]').forEach(b=>b.onclick=()=>{localStorage.setItem('agpeya_'+hour+'_step',b.dataset.jumpStep);const hourButton=document.querySelector(`#shellPrayerSheet [data-hour="${hour}"]`);if(hourButton)hourButton.click();document.getElementById('shellJumpSheet').classList.add('hide');window.scrollTo({top:0,behavior:'smooth'})})}catch(e){host.innerHTML='<p class="jumpHint" style="padding:16px;margin:0">Unable to load this Hour’s prayer list. Please try again.</p>';console.error(e)}}
const boot=()=>ensureUI();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();new MutationObserver(ensureUI).observe(document.body,{childList:true,subtree:true});
})();