(()=>{
const RULE_KEY='copticDailyPrayer_rule_v1',JESUS_KEY='copticDailyPrayer_jesus_count_v1';
const style=document.createElement('style');style.textContent=`.toolSheet{max-height:88vh}.toolIntro{color:var(--muted);line-height:1.55;margin:-8px 0 20px}.jesusPrayer{text-align:center;padding:24px 0 10px}.jesusPrayer .invocation{font:400 25px/1.55 Georgia,serif;max-width:390px;margin:0 auto 28px}.jesusCount{font:700 58px/1 Georgia,serif;color:var(--wine);margin:10px 0 24px}.jesusTap{width:100%;min-height:68px;border:0;border-radius:22px;background:var(--wine);color:#fff;font-weight:800;font-size:15px}.toolLink{border:0;background:transparent;color:var(--wine);font-weight:750;padding:18px}.ruleList{border:1px solid var(--line);border-radius:18px;overflow:hidden}.ruleRow{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;padding:14px;border-bottom:1px solid var(--line)}.ruleRow:last-child{border-bottom:0}.ruleRow strong{display:block;font:700 16px Georgia,serif}.ruleRow small{color:var(--muted)}.ruleRow input{width:22px;height:22px;accent-color:var(--wine)}.ruleFather{display:flex;gap:10px;align-items:flex-start;margin:18px 2px;color:var(--muted);line-height:1.45}.ruleFather input{margin-top:3px;accent-color:var(--wine)}.saveRule{width:100%;min-height:54px;border:0;border-radius:18px;background:var(--wine);color:#fff;font-weight:800}`;document.head.appendChild(style);
function sheet(id){let s=document.getElementById(id);if(!s){s=document.createElement('div');s.id=id;s.className='prayerSheet toolSheet hide';document.body.appendChild(s)}return s}
function close(id){document.getElementById(id)?.classList.add('hide')}
function openJesus(){const s=sheet('jesusPrayerSheet'),n=Math.max(0,Number(localStorage.getItem(JESUS_KEY)||0));s.innerHTML=`<button class="sheetClose" id="jesusClose">Done</button><div class="eyebrow">Prayer Tool</div><h2>Jesus Prayer</h2><p class="toolIntro">A simple counter for the Jesus Prayer. Your count stays only on this device.</p><div class="jesusPrayer"><p class="invocation">Lord Jesus Christ, Son of God, have mercy on me, a sinner.</p><div class="jesusCount" id="jesusCount">${n}</div><button class="jesusTap" id="jesusTap">LORD, HAVE MERCY</button><button class="toolLink" id="jesusReset">Reset</button></div>`;s.classList.remove('hide');document.getElementById('jesusClose').onclick=()=>close('jesusPrayerSheet');document.getElementById('jesusTap').onclick=()=>{const v=Math.max(0,Number(localStorage.getItem(JESUS_KEY)||0))+1;localStorage.setItem(JESUS_KEY,String(v));document.getElementById('jesusCount').textContent=v};document.getElementById('jesusReset').onclick=()=>{localStorage.setItem(JESUS_KEY,'0');document.getElementById('jesusCount').textContent='0'}}
const items=[['first','First Hour','Morning'],['third','Third Hour','9 AM'],['sixth','Sixth Hour','Noon'],['ninth','Ninth Hour','3 PM'],['eleventh','Eleventh Hour','Evening'],['compline','Compline','Before sleep'],['midnight','Midnight Prayer','Night'],['reading','Daily Reading','Lectionary'],['jesus','Jesus Prayer','Optional']];
function getRule(){try{return JSON.parse(localStorage.getItem(RULE_KEY))||{first:true,third:false,sixth:false,ninth:false,eleventh:true,compline:false,midnight:false,reading:true,jesus:true,withFather:false}}catch(e){return{first:true,eleventh:true,reading:true,jesus:true}}}
function openRule(){const r=getRule(),s=sheet('prayerRuleSheet');s.innerHTML=`<button class="sheetClose" id="ruleClose">Done</button><div class="eyebrow">Your Prayer Life</div><h2>Personal Prayer Rule</h2><p class="toolIntro">Choose a simple daily rhythm. This is a personal planning tool and does not replace guidance from your Father of Confession.</p><div class="ruleList">${items.map(([k,t,m])=>`<label class="ruleRow"><span><strong>${t}</strong><small>${m}</small></span><input type="checkbox" data-rule="${k}" ${r[k]?'checked':''}></label>`).join('')}</div><label class="ruleFather"><input type="checkbox" id="ruleFather" ${r.withFather?'checked':''}><span>Set with my Father of Confession</span></label><button class="saveRule" id="ruleSave">Save Prayer Rule</button>`;s.classList.remove('hide');document.getElementById('ruleClose').onclick=()=>close('prayerRuleSheet');document.getElementById('ruleSave').onclick=()=>{const next={};s.querySelectorAll('[data-rule]').forEach(x=>next[x.dataset.rule]=x.checked);next.withFather=document.getElementById('ruleFather').checked;localStorage.setItem(RULE_KEY,JSON.stringify(next));close('prayerRuleSheet');renderRuleSummary()}}
function renderRuleSummary(){const r=getRule(),names=items.filter(([k])=>r[k]).map(([,t])=>t),b=document.querySelector('[data-tool="rule"]');if(!b)return;let sub=b.querySelector('small');if(!sub){sub=document.createElement('small');sub.style.cssText='display:block;color:var(--muted);font-weight:400;margin-top:3px';b.querySelector('b').after(sub)}sub.textContent=names.length?names.slice(0,3).join(' · ')+(names.length>3?' +'+(names.length-3):''):'Not configured'}
function boot(){const more=document.querySelector('[data-screen="more"]');if(!more)return;const buttons=[...more.querySelectorAll('.settingsGroup button')];const rule=buttons.find(b=>b.textContent.includes('Personal Prayer Rule')),jesus=buttons.find(b=>b.textContent.includes('Jesus Prayer'));if(rule){rule.dataset.tool='rule';rule.onclick=openRule}if(jesus)jesus.onclick=openJesus;renderRuleSummary()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();