(function(){
'use strict';
var SERVICES=[{name:'Vespers',items:[['Psalm',['VPsalm']],['Gospel',['VGospel']]]},{name:'Matins',items:[['Psalm',['MPsalm']],['Gospel',['MGospel']]]},{name:'Liturgy',items:[['Pauline',['Pauline']],['Catholic',['Catholic']],['Acts',['Acts']],['Psalm',['LPsalm']],['Gospel',['LGospel']]]}];
var readingData=null,service=2,item=0,readingDate=null,loadedKey='',loading=false,selectedOverride=false;
function id(x){return document.getElementById(x)}
function key(d){var m=String(d.getMonth()+1),day=String(d.getDate());if(m.length<2)m='0'+m;if(day.length<2)day='0'+day;return d.getFullYear()+'-'+m+'-'+day}
function parseKey(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v||''))return null;var p=v.split('-'),d=new Date(Number(p[0]),Number(p[1])-1,Number(p[2]));return key(d)===v?d:null}
function arr(v){return !v?[]:(Array.isArray(v)?v:[v])}
function findReading(keys){if(!readingData)return null;for(var a=0;a<keys.length;a++){var list=arr(readingData[keys[a]]);for(var b=0;b<list.length;b++)if(list[b]&&list[b].chapters&&list[b].chapters.length)return list[b]}return null}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]})}
function reference(r){if(!r)return'';var ch=r.chapters||[],book=r.bookName||'';if(!ch.length)return book;var first=ch[0],last=ch[ch.length-1],fv=first.verses&&first.verses[0]?first.verses[0].num:null,lv=last.verses&&last.verses.length?last.verses[last.verses.length-1].num:null;if(fv==null||lv==null)return book;if(ch.length===1)return book+' '+first.chapterNum+':'+fv+'-'+lv;return book+' '+first.chapterNum+':'+fv+'-'+last.chapterNum+':'+lv}
function verses(r){var out='',ch=r.chapters||[];for(var i=0;i<ch.length;i++){out+='<p>';var vs=ch[i].verses||[];for(var j=0;j<vs.length;j++)out+='<sup class="verseNum">'+esc(vs[j].num)+'</sup>'+esc(vs[j].text)+' ';out+='</p>'}return out}
function styles(){if(id('nativeReadingStyles'))return;var s=document.createElement('style');s.id='nativeReadingStyles';s.textContent='.serviceTabs{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;padding:4px;background:var(--soft);border-radius:15px;margin:8px 0 14px}.serviceTabs button{border:0;background:transparent;min-height:42px;border-radius:12px;color:var(--muted);font-weight:750}.serviceTabs button.active{background:#fff;color:var(--wine);box-shadow:0 1px 5px rgba(50,25,20,.08)}.readingDateNote{font-size:12px;color:var(--muted);margin:4px 0 18px}.readingBody{padding:0 0 120px}.lectionaryCard{padding:18px 2px 12px}.readingKind{color:var(--wine);font-size:12px;font-weight:800;letter-spacing:.18em;text-transform:uppercase;margin-bottom:8px}.readingReference{font:700 31px/1.12 Georgia,serif;margin:0 0 22px}.readingVerses{font:400 23px/1.72 Georgia,serif}.readingVerses p{margin:0 0 18px}.verseNum{font:700 11px/1 system-ui,sans-serif;color:var(--wine);vertical-align:super;margin-right:5px}.readingEmpty{padding:34px 0;color:var(--muted);font-size:16px;line-height:1.55}.readingFoot{display:flex;gap:10px;margin-top:30px}.readingFoot button{flex:1;min-height:52px;border:1px solid var(--line);border-radius:18px;background:#fff;font-weight:700}.readingFoot .markRead{background:var(--wine);color:#fff;border-color:var(--wine)}';document.head.appendChild(s)}
function build(){var screen=id('readings');if(!screen||id('nativeServiceTabs'))return;styles();screen.innerHTML='<header class="pageHead"><div class="eyebrow">Daily Lectionary</div><h1>Today’s Readings</h1><p class="subtitle">The appointed readings in the Coptic Church.</p></header><div class="serviceTabs" id="nativeServiceTabs"></div><div class="readingTabs" id="nativeReadingTabs"></div><div class="readingDateNote" id="nativeReadingDate"></div><div class="readingBody" id="nativeReadingBody"></div>';var svc=id('nativeServiceTabs');for(var i=0;i<SERVICES.length;i++){var b=document.createElement('button');b.type='button';b.setAttribute('data-service',String(i));b.textContent=SERVICES[i].name;b.onclick=function(){service=Number(this.getAttribute('data-service'));item=0;render()};svc.appendChild(b)}}
function renderTabs(){var svc=id('nativeServiceTabs'),tabs=id('nativeReadingTabs');if(!svc||!tabs)return;var bs=svc.getElementsByTagName('button');for(var i=0;i<bs.length;i++)bs[i].className=i===service?'active':'';tabs.innerHTML='';var items=SERVICES[service].items;for(var j=0;j<items.length;j++){var b=document.createElement('button');b.type='button';b.setAttribute('data-item',String(j));b.className=j===item?'active':'';b.textContent=items[j][0];b.onclick=function(){item=Number(this.getAttribute('data-item'));render()};tabs.appendChild(b)}}
function render(){build();renderTabs();var body=id('nativeReadingBody');if(!body)return;if(readingDate){var opts={weekday:'long',month:'long',day:'numeric'},prefix=selectedOverride?'Selected Church day':(service===0&&key(readingDate)!==key(new Date())?'Tonight’s Vespers':'Coptic Lectionary');id('nativeReadingDate').textContent=prefix+' · '+readingDate.toLocaleDateString(undefined,opts)}if(!readingData){body.innerHTML='<div class="readingEmpty">Loading the Coptic Lectionary…</div>';return}var label=SERVICES[service].items[item][0],r=findReading(SERVICES[service].items[item][1]);if(!r){body.innerHTML='<div class="readingEmpty">No '+esc(SERVICES[service].name)+' '+esc(label)+' reading was returned for this Church day.</div>';return}var store='copticDailyPrayer_reading_'+key(readingDate)+'_'+SERVICES[service].name+'_'+label,done=false;try{done=localStorage.getItem(store)==='1'}catch(e){}body.innerHTML='<article class="lectionaryCard"><div class="readingKind">'+esc(SERVICES[service].name)+' · '+esc(label)+'</div><h2 class="readingReference">'+esc(reference(r))+'</h2><div class="readingVerses">'+verses(r)+'</div><div class="readingFoot"><button id="nativeReadingPrev">Previous</button><button class="markRead" id="nativeReadingDone">'+(done?'Read ✓':'Mark as Read')+'</button><button id="nativeReadingNext">Next</button></div></article>';id('nativeReadingPrev').onclick=function(){move(-1)};id('nativeReadingNext').onclick=function(){move(1)};id('nativeReadingDone').onclick=function(){try{localStorage.setItem(store,'1')}catch(e){}render()}}
function move(d){var s=service,i=item+d;if(i<0){s--;if(s<0)return;i=SERVICES[s].items.length-1}else if(i>=SERVICES[s].items.length){s++;if(s>=SERVICES.length)return;i=0}service=s;item=i;render();window.scrollTo(0,0)}
function desiredDate(){var stored='';try{stored=sessionStorage.getItem('copticDailyPrayer_selectedReadingDate')||'';if(stored)sessionStorage.removeItem('copticDailyPrayer_selectedReadingDate')}catch(e){}var chosen=parseKey(stored);if(chosen){selectedOverride=true;return chosen}selectedOverride=false;var now=new Date(),d=new Date(now.getFullYear(),now.getMonth(),now.getDate());if(now.getHours()>=17)d.setDate(d.getDate()+1);return d}
function load(force){if(loading)return;build();var now=new Date(),next=desiredDate(),nextKey=key(next);if(!force&&readingData&&loadedKey===nextKey)return;readingDate=next;if(selectedOverride)service=2;else service=now.getHours()>=17?0:2;item=0;loadedKey=nextKey;readingData=null;loading=true;render();fetch('/api/church?path='+encodeURIComponent('/readings/'+loadedKey+'?detailed=true'),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('readings '+r.status);return r.json()}).then(function(j){readingData=j.data||j;loading=false;render()}).catch(function(){loading=false;var body=id('nativeReadingBody');if(body)body.innerHTML='<div class="readingEmpty">These readings could not be loaded. Please try again.</div>'})}
function route(){if(location.hash==='#readings')load(false)}
window.openLectionaryDate=function(dateKey){var d=parseKey(dateKey);if(!d)return;try{sessionStorage.setItem('copticDailyPrayer_selectedReadingDate',dateKey)}catch(e){}if(location.hash==='#readings')load(true);else location.hash='#readings'};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){build();route()});else{build();route()}window.addEventListener('hashchange',route);
})();
