(()=>{
const TYPES=[['Psalm',['MPsalm','VPsalm','LPsalm','EPPsalm']],['Gospel',['MGospel','VGospel','LGospel','EPGospel','Gospel']],['Pauline',['Pauline']],['Catholic',['Catholic']],['Acts',['Acts']]];let readingData=null,current=0;
const style=document.createElement('style');style.textContent=`.readingTabs{overflow-x:auto;scrollbar-width:none}.readingTabs::-webkit-scrollbar{display:none}.readingTabs button{white-space:nowrap}.readingBody.liveReading{padding:0 0 120px}.lectionaryCard{padding:28px 4px 12px}.readingKind{color:var(--wine);font-size:12px;font-weight:800;letter-spacing:.18em;text-transform:uppercase;margin-bottom:8px}.readingReference{font:700 31px/1.12 Georgia,serif;color:var(--ink);margin:0 0 22px}.readingVerses{font:400 23px/1.72 Georgia,serif;color:var(--ink)}.readingVerses p{margin:0 0 18px}.verseNum{font:700 11px/1 system-ui,sans-serif;color:var(--wine);vertical-align:super;margin-right:5px}.readingEmpty{padding:34px 0;color:var(--muted);font-size:16px;line-height:1.55}.readingFoot{display:flex;gap:12px;margin-top:30px}.readingFoot button{flex:1;min-height:52px;border:1px solid var(--line);border-radius:18px;background:#fff;color:var(--ink);font-weight:700}.readingFoot .markRead{background:var(--wine);color:white;border-color:var(--wine)}.readDone{opacity:.72}`;document.head.appendChild(style);
function dateKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function arr(v){return !v?[]:Array.isArray(v)?v:[v]}
function findReading(keys){for(const key of keys){for(const r of arr(readingData?.[key]))if(r?.chapters?.length)return{key,r}}return null}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function reference(r){if(!r)return'';const chapters=r.chapters||[],book=r.bookName||'';if(!chapters.length)return book;const first=chapters[0],last=chapters[chapters.length-1],fv=first.verses?.[0]?.num,lv=last.verses?.[last.verses.length-1]?.num;if(chapters.length===1&&fv!=null&&lv!=null)return `${book} ${first.chapterNum}:${fv}-${lv}`;return book}
function verses(r){return(r.chapters||[]).map(ch=>`<p>${(ch.verses||[]).map(v=>`<sup class="verseNum">${esc(v.num)}</sup>${esc(v.text)} `).join('')}</p>`).join('')}
function render(){const tabs=[...document.querySelectorAll('[data-screen="readings"] .readingTabs button')],body=document.querySelector('[data-screen="readings"] .readingBody');if(!body)return;tabs.forEach((b,i)=>b.classList.toggle('active',i===current));const [label,keys]=TYPES[current],hit=findReading(keys);body.classList.add('liveReading');if(!readingData){body.innerHTML='<div class="readingEmpty">Loading today’s Coptic Lectionary…</div>';return}if(!hit){body.innerHTML=`<div class="readingEmpty">No ${esc(label)} reading was returned for this Church day.</div>`;return}const done=localStorage.getItem('copticDailyPrayer_reading_'+dateKey()+'_'+label)==='1';body.innerHTML=`<article class="lectionaryCard"><div class="readingKind">${esc(label)}</div><h2 class="readingReference">${esc(reference(hit.r))}</h2><div class="readingVerses">${verses(hit.r)}</div><div class="readingFoot"><button id="readingPrev" ${current===0?'disabled':''}>Previous</button><button class="markRead ${done?'readDone':''}" id="readingDone">${done?'Read ✓':'Mark as Read'}</button><button id="readingNext" ${current===TYPES.length-1?'disabled':''}>Next</button></div></article>`;document.getElementById('readingPrev').onclick=()=>switchTo(current-1);document.getElementById('readingNext').onclick=()=>switchTo(current+1);document.getElementById('readingDone').onclick=()=>{localStorage.setItem('copticDailyPrayer_reading_'+dateKey()+'_'+label,'1');render()}}
function switchTo(i){if(i<0||i>=TYPES.length)return;current=i;render();window.scrollTo({top:0,behavior:'smooth'})}
async function load(){render();try{const r=await fetch('/api/church?path='+encodeURIComponent('/readings/'+dateKey()+'?detailed=true'));const j=await r.json();readingData=j.data||j;render()}catch(e){const body=document.querySelector('[data-screen="readings"] .readingBody');if(body)body.innerHTML='<div class="readingEmpty">Today’s readings could not be loaded. Please try again.</div>';console.error(e)}}
function boot(){const tabs=[...document.querySelectorAll('[data-screen="readings"] .readingTabs button')];tabs.forEach((b,i)=>b.onclick=()=>switchTo(i));load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();