(()=>{
const SERVICES=[{name:'Vespers',items:[['Psalm',['VPsalm']],['Gospel',['VGospel']]]},{name:'Matins',items:[['Psalm',['MPsalm']],['Gospel',['MGospel']]]},{name:'Liturgy',items:[['Pauline',['Pauline']],['Catholic',['Catholic']],['Acts',['Acts']],['Psalm',['LPsalm']],['Gospel',['LGospel']]]}];let readingData=null,service=0,item=0,readingDate=null;
const style=document.createElement('style');style.textContent=`.serviceTabs{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;padding:4px;background:var(--soft);border-radius:15px;margin:8px 0 14px}.serviceTabs button{border:0;background:transparent;min-height:42px;border-radius:12px;color:var(--muted);font-weight:750}.serviceTabs button.active{background:#fff;color:var(--wine);box-shadow:0 1px 5px rgba(50,25,20,.08)}.readingTabs{overflow-x:auto;scrollbar-width:none;margin-bottom:6px}.readingTabs::-webkit-scrollbar{display:none}.readingTabs button{white-space:nowrap}.readingDateNote{font-size:12px;color:var(--muted);margin:4px 0 18px}.readingBody.liveReading{padding:0 0 120px}.lectionaryCard{padding:24px 4px 12px}.readingKind{color:var(--wine);font-size:12px;font-weight:800;letter-spacing:.18em;text-transform:uppercase;margin-bottom:8px}.readingReference{font:700 31px/1.12 Georgia,serif;color:var(--ink);margin:0 0 22px}.readingVerses{font:400 23px/1.72 Georgia,serif;color:var(--ink)}.readingVerses p{margin:0 0 18px}.verseNum{font:700 11px/1 system-ui,sans-serif;color:var(--wine);vertical-align:super;margin-right:5px}.readingEmpty{padding:34px 0;color:var(--muted);font-size:16px;line-height:1.55}.readingFoot{display:flex;gap:10px;margin-top:30px}.readingFoot button{flex:1;min-height:52px;border:1px solid var(--line);border-radius:18px;background:#fff;color:var(--ink);font-weight:700}.readingFoot .markRead{background:var(--wine);color:white;border-color:var(--wine)}.readDone{opacity:.72}`;document.head.appendChild(style);
function localKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseKey(k){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(k||'');return m?new Date(+m[1],+m[2]-1,+m[3]):null}
function effectiveDate(){const selected=sessionStorage.getItem('copticDailyPrayer_selectedReadingDate');if(selected){sessionStorage.removeItem('copticDailyPrayer_selectedReadingDate');return parseKey(selected)||new Date()}const now=new Date();if(now.getHours()>=17){const d=new Date(now);d.setDate(d.getDate()+1);return d}return now}
function arr(v){return !v?[]:Array.isArray(v)?v:[v]}
function findReading(keys){for(const key of keys){for(const r of arr(readingData?.[key]))if(r?.chapters?.length)return{key,r}}return null}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function reference(r){if(!r)return'';const chapters=r.chapters||[],book=r.bookName||'';if(!chapters.length)return book;const first=chapters[0],last=chapters[chapters.length-1],fv=first.verses?.[0]?.num,lv=last.verses?.[last.verses.length-1]?.num;if(chapters.length===1&&fv!=null&&lv!=null)return `${book} ${first.chapterNum}:${fv}-${lv}`;return book}
function verses(r){return(r.chapters||[]).map(ch=>`<p>${(ch.verses||[]).map(v=>`<sup class="verseNum">${esc(v.num)}</sup>${esc(v.text)} `).join('')}</p>`).join('')}
function ensureUI(){const screen=document.querySelector('[data-screen="readings"]'),old=screen?.querySelector('.readingTabs');if(!screen||!old)return;let svc=screen.querySelector('.serviceTabs');if(!svc){svc=document.createElement('div');svc.className='serviceTabs';svc.innerHTML=SERVICES.map((s,i)=>`<button data-service="${i}">${s.name}</button>`).join('');old.before(svc);const note=document.createElement('div');note.className='readingDateNote';note.id='readingDateNote';old.after(note);svc.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>switchService(Number(b.dataset.service)))}renderTabs()}
function renderTabs(){const svc=document.querySelector('.serviceTabs'),tabs=document.querySelector('[data-screen="readings"] .readingTabs');if(!svc||!tabs)return;svc.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===service));tabs.innerHTML=SERVICES[service].items.map(([name],i)=>`<button class="${i===item?'active':''}" data-reading-item="${i}">${name}</button>`).join('');tabs.querySelectorAll('[data-reading-item]').forEach(b=>b.onclick=()=>{item=Number(b.dataset.readingItem);render()});const note=document.getElementById('readingDateNote');if(note&&readingDate){const day=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(readingDate);note.textContent=service===0&&readingDate.toDateString()!==new Date().toDateString()?`Tonight’s Vespers readings for ${day}`:`${SERVICES[service].name} readings for ${day}`}}
function render(){ensureUI();renderTabs();const body=document.querySelector('[data-screen="readings"] .readingBody');if(!body)return;const [label,keys]=SERVICES[service].items[item],hit=findReading(keys);body.classList.add('liveReading');if(!readingData){body.innerHTML='<div class="readingEmpty">Loading the Coptic Lectionary…</div>';return}if(!hit){body.innerHTML=`<div class="readingEmpty">No ${esc(SERVICES[service].name)} ${esc(label)} reading was returned for this Church day.</div>`;return}const k=localKey(readingDate),done=localStorage.getItem('copticDailyPrayer_reading_'+k+'_'+SERVICES[service].name+'_'+label)==='1';body.innerHTML=`<article class="lectionaryCard"><div class="readingKind">${esc(SERVICES[service].name)} · ${esc(label)}</div><h2 class="readingReference">${esc(reference(hit.r))}</h2><div class="readingVerses">${verses(hit.r)}</div><div class="readingFoot"><button id="readingPrev">Previous</button><button class="markRead ${done?'readDone':''}" id="readingDone">${done?'Read ✓':'Mark as Read'}</button><button id="readingNext">Next</button></div></article>`;document.getElementById('readingPrev').onclick=()=>move(-1);document.getElementById('readingNext').onclick=()=>move(1);document.getElementById('readingDone').onclick=()=>{localStorage.setItem('copticDailyPrayer_reading_'+k+'_'+SERVICES[service].name+'_'+label,'1');render()}}
function switchService(i){service=Math.max(0,Math.min(i,SERVICES.length-1));item=0;render();window.scrollTo({top:0,behavior:'smooth'})}
function move(delta){let s=service,i=item+delta;if(i<0){s--;if(s<0)return;i=SERVICES[s].items.length-1}else if(i>=SERVICES[s].items.length){s++;if(s>=SERVICES.length)return;i=0}service=s;item=i;render();window.scrollTo({top:0,behavior:'smooth'})}
async function load(){readingDate=effectiveDate();const evening=new Date().getHours()>=17&&!sessionStorage.getItem('copticDailyPrayer_selectedReadingDate');service=evening?0:2;item=0;render();try{const r=await fetch('/api/church?path='+encodeURIComponent('/readings/'+localKey(readingDate)+'?detailed=true'));const j=await r.json();readingData=j.data||j;render()}catch(e){const body=document.querySelector('[data-screen="readings"] .readingBody');if(body)body.innerHTML='<div class="readingEmpty">These readings could not be loaded. Please try again.</div>';console.error(e)}}
function boot(){ensureUI();load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();